Documentación - Introducción y Estado del arte
Slowmybrosh/TFG-DietPlanner pull request #10
Opened 2023-04-11 16:20 UTC by Slowmybrosh

Se han cambiado la mayoría de placeholder de la plantilla. Además se han añadido las secciones: 
- Introducción
- Estado del arte

2023-04-12 08:14 UTC, JJ commented
Todos los PRs tienen que resolver uno o varios issues, y estar en un milestone.

2023-04-12 08:22 UTC, JJ requested changes
Sería mejor que lo dividieras en varios PRs. La parte de eliminación del boilerplate está en general bien, aunque también tendrías que crear un issue para eso. El resto, es mejor que lo dejes en un PR aparte, que va a requerir más trabajo.

2023-04-12 08:22 UTC, JJ commented on doc/Secciones/01_Introduccion.tex
> +En este capítulo se describirá la motivación y los objetivos principales del proyecto.
Tiene que avanzar la historia de usuario del tribunal, al menos.

2023-04-12 08:22 UTC, JJ commented on doc/Secciones/01_Introduccion.tex
> +    \item Ayudar a las personas con intolerancias o alergias a crear una dieta adaptada a su alimentación.
Por favor, lee lo de [los objetivos](https://jjmerelo.medium.com/c%C3%B3mo-formular-buenos-objetivos-en-un-trabajo-7e68abf10028). "Ayudar" no es cuantificable.

2023-04-12 08:22 UTC, JJ commented on doc/Secciones/01_Introduccion.tex
> +    \item Reducir el tiempo que pasan las personas decidiendo que comer.
"Reducir" es cuantificable, pero en la formulación del problema y/o en los user journeys tienes que dejar claramente escrito cuál es ese tiempo. Si vas a cambiar "buscar en google platos con X" por "buscar en Burger Kris platos con X" no habrá mucha ganancia.

2023-04-12 08:22 UTC, JJ commented on doc/Secciones/02_Estado_del_arte.tex
> +Después de una exhaustiva investigación en este campo, se han encontrado multitud de aplicaciones que te ayudan a gestionar tu dieta o bien para encontrar recetas que contengan los ingredientes que s
Si es exhaustiva, tienes que mostrar algunas citas o decir cómo la has llevado a cabo.
Aquí también tienes que decidir si lo que quieres "vender" es el algoritmo que vas a implementar o el producto final, del que puede haber muchos.

2023-04-12 08:22 UTC, JJ commented on doc/Secciones/02_Estado_del_arte.tex
> +En dicha investigación se ha encontrado una herramienta muy interesante orientada a profesionales, denominada \emph{Diet Creator}, que permite crear dietas controlando multitud de parámetros. Esta cu
Comenta coste, por ejemplo, y plataformas.
También ten en cuenta a quién va dirigido; este es a profesionales. Si tus "personas" no los incluyen, no es competencia de ninguna forma.

2023-04-12 08:22 UTC, JJ commented on doc/Secciones/02_Estado_del_arte.tex
> +Otra de las aplicaciones más interesantes que se encontraron fue \href{https://www.eatthismuch.com/}{EatThisMuch}.Esta es una aplicación web, también disponible para Android e IOS, que permite genera
Espacio después de punto. ¿No te pilla eso el textidote?

2023-04-12 08:22 UTC, JJ commented on doc/Secciones/02_Estado_del_arte.tex
> +En un apartado más técnico, el problema al que nos enfrentamos para la creación de una dieta es el muy conocido ``problema de la mochila"\cite{mochila}. Se trata de un problema de optimización combin
Aquí es mejor que uses una cita de verdad

2023-04-12 08:22 UTC, JJ commented on doc/Secciones/02_Estado_del_arte.tex
> +Por otra parte, otro de los pilares fundamentales de la aplicación que se plantea desarrollar son las bases de datos. Este término se escuchó por primera vez en 1963. Su definición, por aquel entonce
Uf, no, por favor, esto no. En el apartado de implementación es posible que sea relevante, aquí suena a relleno.

2023-04-12 08:22 UTC, JJ commented on doc/Secciones/02_Estado_del_arte.tex
> +Debido a la gran cantidad de lenguajes de programación, se debe escoger cuidadosamente cual utilizar. Algunos de los lenguajes que se recomiendan \cite{known-lan} para aplicaciones en la nube son:
Igual, apartado de implementación. Esto está enfocado a justificar decisiones, no tanto a presentar el estado del arte "de lenguajes"

2023-04-12 08:22 UTC, JJ commented on doc/Secciones/02_Estado_del_arte.tex
> +    \item NodeJS
Es un intérprete de JavaScript

2023-04-21 05:44 UTC, JJ commented
Trata de hacer los mensajes de commit un poco más informativos. Aunque digas "se avanza", di algo más: documentación, se añaden detalles... Además de que, en general, no "se avanza" una historia de usuarios directamente. Tienes que desarrollarla en issues.

2023-04-21 05:55 UTC, JJ requested changes
El obstáculo principal es la correcta formulación de los objetivos; es la parte más importante del trabajo, porque a partir de eso se hace todo el resto.

2023-04-21 05:55 UTC, JJ commented on doc/Secciones/01_Introduccion.tex
> +    \item Diseñar e implementar un software que permita a los usuarios la creación de una dieta completamente personalizada basada en una serie de parámetros. Teniendo en cuenta posibles intolerancia
Los objetivos tienen siempre que ser resolver un problema, sin fijar una solución específica. No es lo mismo "una dieta" que "platos con componentes sustituidos" que "un plan semanal de comidas" que otras muchas cosas. Tienes que
1. Proponer los objetivos principales del trabajo, *siempre en el dominio del problema*
2. En milestones, decir qué pasos vas a dar para acercarte a ese objetivo; lo puedes poner como subobjetivos

Eso te ayudará aabordar el problema y dividirlo en etapas o partes que sean más fácilmente abordables.

2023-04-21 05:55 UTC, JJ commented on doc/Secciones/01_Introduccion.tex
> +    \item Diseñar y desplegar una solución en la nube para alojar el software desarrollado. Brindando escalabilidad y alta disponibilidad a los usuarios.
Igualmente, estás comprometiéndote con una solución antes de hacer un verdadero análisis de las soluciones del usuario. Puede ser eventualmente una solución en la nube, puede ser un backend que se pueda usar desde diferentes soluciones, puede ser un app o puede ser una aplicación de escritorio. Dependerá de las necesidades específicas del usuario.

2023-04-21 05:55 UTC, JJ commented on doc/Secciones/02_Estado_del_arte.tex
> +Después de una investigación inicial en este campo buscando en diversos blogs de nutrición como \emph{HealthLine}\cite{Healthline2022} y revistas como \emph{Bussines Insider}\cite{BusinessInsider2021
las oraciones relativas no llevan nunca punto al principio. Tampoco lleva acento Dónde, porque no es interrogativo.

2023-04-21 05:55 UTC, JJ commented on doc/Secciones/02_Estado_del_arte.tex
> +El software que se busca desarrollar, tiene como objetivo llegar al usuario final. Permitiendo así que cualquier persona pueda generar una dieta adaptada a sus necesidades. Por ello, se venderá un pr
Una vez más, no digas lo que va a hacer el software. Te puedes quedar corto, y realmente el desarrollo ágil viene a decir que se va descubriendo lo que va a hacer poco a poco, según vayas "empatizando" con el usuario y descubriendo qué es lo que quiere.

2023-04-21 05:55 UTC, JJ commented on doc/Secciones/02_Estado_del_arte.tex
> +En un apartado más técnico, el problema al que nos enfrentamos para la creación de una dieta es el muy conocido ``problema de la mochila", listado en los ``21 problemas NP-Completos de Richard Karp".
Esto no pega en el estado del arte; realmente no es parte del estado del arte.
Si quieres encajar aquí un estudio de los algoritmos que hay para optimizar dietas, tendríás que hacer un pequeño estudio y buscar algún artículo sobre el tema; más adelante, en el apartado de implementación, harías la elección del más adecuado o te comprometerías con uno de ellos.

2023-04-21 05:55 UTC, JJ commented on doc/bibliografia.bib
> +    url     = {https://funsapa.org/alergia-alimentaria/incidencia/}
Las webs es mejor que simplemente las enlacéis.

2023-05-02 07:54 UTC, JJ requested changes
Ahí va otra revisioncilla, a ver si te sirve.

2023-05-02 07:54 UTC, JJ commented on doc/Secciones/01_Introduccion.tex
> +En este capítulo se describirá la motivación y los objetivos principales del proyecto.
... mediante una serie de issues que crees

2023-05-09 06:45 UTC, JJ commented
A ver, que estuviste en IV. Problemillas
1. Sigues sin enlazar ni issues ni de estos a HUs.
2. No puedes empezar por el milestone 6. Se empieza por el 0, que es esencialmente infraestructura para que todo vaya bien o introducción.
3. NO has contestado a alguno de los comentarios.

2023-05-09 13:43 UTC, Slowmybrosh commented
> A ver, que estuviste en IV. Problemillas
> 
> 1. Sigues sin enlazar ni issues ni de estos a HUs. (Lo has hecho en los mensajes de commit, pero también en el cuerpo del PR, puedes editarlo y añadirlos; debe quedar claro cuál es el ámbito del PR)
> 2. No puedes empezar por el milestone 6. Se empieza por el 0, que es esencialmente infraestructura para que todo vaya bien o introducción.
> 3. NO has contestado a alguno de los comentarios.

Lo de los milestone es porque la documentación es como lo último que se iba a completar paralelamente con el desarrollo del proyecto y los comentarios es debido a cerrar las conversaciones cuando no tienen discusión y cambiar lo demás porque no hay mucho que discutir.

El primer punto es totalmente cierto que debería añadir un comentario detallando todos los cambios realizados, enlazando tanto la HU como los issues trabajados. Y es una cosa que se me ha estado olvidando

2023-05-09 15:25 UTC, JJ commented
> > A ver, que estuviste en IV. Problemillas
> > 
> > 1. Sigues sin enlazar ni issues ni de estos a HUs. (Lo has hecho en los mensajes de commit, pero también en el cuerpo del PR, puedes editarlo y añadirlos; debe quedar claro cuál es el ámbito del PR)
> > 2. No puedes empezar por el milestone 6. Se empieza por el 0, que es esencialmente infraestructura para que todo vaya bien o introducción.
> > 3. NO has contestado a alguno de los comentarios.
> 
> Lo de los milestone es porque la documentación es como lo último que se iba a completar paralelamente con el desarrollo del proyecto y los comentarios es debido a cerrar las conversaciones cuando no tienen discusión y cambiar lo demás porque no hay mucho que discutir.

La documentación forma parte de todos y cada uno de los PMVs, tienes que documentarlo o no es válido.  Igual puedes reconsiderar que sea un milestone. Recuerda que los milestones no son tareas, son productos que entregas al cliente/clientes.

2023-05-09 15:32 UTC, Slowmybrosh commented
> > > A ver, que estuviste en IV. Problemillas
> > > 
> > > 1. Sigues sin enlazar ni issues ni de estos a HUs. (Lo has hecho en los mensajes de commit, pero también en el cuerpo del PR, puedes editarlo y añadirlos; debe quedar claro cuál es el ámbito del PR)
> > > 2. No puedes empezar por el milestone 6. Se empieza por el 0, que es esencialmente infraestructura para que todo vaya bien o introducción.
> > > 3. NO has contestado a alguno de los comentarios.
> > 
> > 
> > Lo de los milestone es porque la documentación es como lo último que se iba a completar paralelamente con el desarrollo del proyecto y los comentarios es debido a cerrar las conversaciones cuando no tienen discusión y cambiar lo demás porque no hay mucho que discutir.
> 
> La documentación forma parte de todos y cada uno de los PMVs, tienes que documentarlo o no es válido. Igual puedes reconsiderar que sea un milestone. Recuerda que los milestones no son tareas, son productos que entregas al cliente/clientes.

Si, voy a eliminar el milestone de documentación y asignar el PR a M0 ya que se trata de la introducción del proyecto

2023-05-11 13:33 UTC, Slowmybrosh commented
En los últimos cambios se han introducido las siguientes mejoras:

- Se ha avanzado #8 añadiendo una introducción y estado del arte para proponer una documentación coherente y completa del proyecto.
- Se han actualizado los objetivos (#13) para que sean alcanzables y medibles. Teniendo en cuenta las historias de usuario propuestas y sus correspondientes milestones.
- Siguiendo #11, se ha eliminado todo lo sobrante en el estado del arte y se moverá a un capítulo más apropiado. 
- Se ha cambiado el hiperlink a la página de FSA por una cita con la correspondiente información

2023-05-11 13:33 UTC, Slowmybrosh commented
En los últimos cambios se han introducido las siguientes mejoras:

- Se ha avanzado #8 añadiendo una introducción y estado del arte para proponer una documentación coherente y completa del proyecto.
- Se han actualizado los objetivos (#13) para que sean alcanzables y medibles. Teniendo en cuenta las historias de usuario propuestas y sus correspondientes milestones.
- Siguiendo #11, se ha eliminado todo lo sobrante en el estado del arte y se moverá a un capítulo más apropiado. 
- Se ha cambiado el hiperlink a la página de FSA por una cita con la correspondiente información

2023-05-11 13:34 UTC, Slowmybrosh commented
@JJ Esto está mejor?

2023-05-11 16:04 UTC, JJ commented
> @JJ Esto está mejor?

Vamos a verlo

2023-05-11 16:05 UTC, JJ commented
> En los últimos cambios se han introducido las siguientes mejoras:
> 
>     * Se ha avanzado [[HU04] Miembro del tribunal - Criterios de Evaluación #8](https://github.com/Slowmybrosh/TFG-DietPlanner/issues/8) añadiendo una introducción y estado del arte para proponer una documentación coherente y completa del proyecto.
> 
>     * Se han actualizado los objetivos ([Corregir objetivos #13](https://github.com/Slowmybrosh/TFG-DietPlanner/issues/13)) para que sean alcanzables y medibles. Teniendo en cuenta las historias de usuario propuestas y sus correspondientes milestones.
> 
>     * Siguiendo [Afinar el estado del arte #11](https://github.com/Slowmybrosh/TFG-DietPlanner/issues/11), se ha eliminado todo lo sobrante en el estado del arte y se moverá a un capítulo más apropiado.
> 
>     * Se ha cambiado el hiperlink a la página de FSA por una cita con la correspondiente información

Esto tiene que estar en el cuerpo del PR. La diferencia entre el cuerpo del PR y los comentarios es que el cuerpo del PR se convierte en un commit, y es entonces cuando aparecen las referencias (y cierres en su caso) de issues. Si lo pones en un comentario no sucede eso.

2023-05-11 16:05 UTC, JJ commented on doc/Secciones/01_Introduccion.tex
> +En la actualidad, debido a una gran concienciación por parte de diferentes organismos orientados la salud, ha aumentado la preocupación por mantener una alimentación saludable y equilibrada. Sin emba
Los organismos no se conciencian, al revés, tratan de concienciar a la gente.

2023-05-11 16:07 UTC, JJ commented on doc/Secciones/01_Introduccion.tex
> +    \item Diseñar e implementar un algoritmo que identifique y sustituya ingredientes en una receta según las intolerancias alimentarias del usuario y mantenga la coherencia de la receta.
Un objetivo no es una tarea, y está siempre en el dominio del problema. Esto es lo que quieres hacer para resolver el problema, pero ¿qué problema quieres resolver o qué parte del problema que deberías haber anunciado arriba?

2023-05-11 18:02 UTC, Slowmybrosh commented on doc/Secciones/01_Introduccion.tex
> +Lo que se plantea es crear una aplicación que ayude al usuario en la tarea de planear que comer, creando una dieta completa y totalmente equilibrada adaptada completamente a sus necesidades. Que no s
El problema no es "no saber planear", sino la dificultad en planear una dieta equilibrada ajustada a sus necesidades. Una persona que coma "sano" alimentandose solo de ensaladas no está supliendo su cuerpo con una serie de nutrientes necesarios, por muy sana que sea dicha dieta no es equilibrada.

2023-05-11 18:02 UTC, Slowmybrosh commented on doc/Secciones/01_Introduccion.tex
> +    \item Diseñar e implementar un algoritmo que identifique y sustituya ingredientes en una receta según las intolerancias alimentarias del usuario y mantenga la coherencia de la receta.
Quiero solucionar el problema que tienen algunos usuarios a la hora de llevar una dieta equilibrada decidiendo que comer. En este caso el objetivo resuelve la dificultad que puedan tener diversos usuarios con alergias o intolerancias a la hora de elaborar recetas, sin que tengan que buscar una receta alternativa

2023-05-11 18:03 UTC, Slowmybrosh commented on doc/Secciones/01_Introduccion.tex
> +        \item Desarrollar una base de datos de ingredientes y alternativas para los casos de intolerancias alimentarias.
Ciertamente, todavía no puedo saber con certeza que tecnología se usará para almacenar los datos y organizar un sistema de recomendación de ingredientes

2023-05-12 05:30 UTC, JJ commented on doc/Secciones/01_Introduccion.tex
> +Lo que se plantea es crear una aplicación que ayude al usuario en la tarea de planear que comer, creando una dieta completa y totalmente equilibrada adaptada completamente a sus necesidades. Que no s
Pues ese tipo de cosas es lo que tienes que plantear como problema.

2023-05-12 05:31 UTC, JJ commented on doc/Secciones/01_Introduccion.tex
> +    \item Diseñar e implementar un algoritmo que identifique y sustituya ingredientes en una receta según las intolerancias alimentarias del usuario y mantenga la coherencia de la receta.
Pero ¿los usuarios con alergias o intolerancias son un cliente específico, o forman parte de la clientela general que has mencionado arriba? ¿Cuál es el contexto, además? ¿Quieres plantear platos que no incluyan los componentes a los que haya alergia o plantear posibles sustituciones con sabores similares?

2023-05-12 05:32 UTC, JJ commented on doc/Secciones/01_Introduccion.tex
> +        \item Desarrollar una base de datos de ingredientes y alternativas para los casos de intolerancias alimentarias.
Además, tampoco sabes si va a haber sustitutos o si la sustitución va a ser uno a uno...

2023-05-12 14:55 UTC, Slowmybrosh commented on doc/Secciones/01_Introduccion.tex
> +Lo que se plantea es crear una aplicación que ayude al usuario en la tarea de planear que comer, creando una dieta completa y totalmente equilibrada adaptada completamente a sus necesidades. Que no s
¿Eso es lo que debería desarrollar? Esto del objetivo se me está haciendo ya cuesta arriba, y eso que he seguido avanzando por otro lado para no quedarme muy atrás

2023-05-12 14:57 UTC, Slowmybrosh commented on doc/Secciones/01_Introduccion.tex
> +    \item Diseñar e implementar un algoritmo que identifique y sustituya ingredientes en una receta según las intolerancias alimentarias del usuario y mantenga la coherencia de la receta.
En dicho objetivo sería parte de la clientela específica, pero dentro de la aplicación general estaría orientada a todos los usuarios en general. Se busca ofertar recetas que, en caso de tener un ingrediente problemático lo sustituya por otro aceptable dentro de unos parámetros

2023-05-12 14:58 UTC, Slowmybrosh commented on doc/Secciones/01_Introduccion.tex
> +    \item Diseñar e implementar un algoritmo que identifique y sustituya ingredientes en una receta según las intolerancias alimentarias del usuario y mantenga la coherencia de la receta.
Entonces, como debería enfocar esta parte del objetivo? He leído el articulo que me mandaste cinco o seis veces y sigo sin saber muy bien que me está faltando para un correcto enfoque de los objetivos

2023-05-15 08:04 UTC, JJ commented on doc/Secciones/01_Introduccion.tex
> +Lo que se plantea es crear una aplicación que ayude al usuario en la tarea de planear que comer, creando una dieta completa y totalmente equilibrada adaptada completamente a sus necesidades. Que no s
En realidad, es la parte esencial del proyecto; son los cimientos y sin ello todo se cae. Hablas de una *dieta* *equilibrada* ajustada a sus *necesidades* . Tienes entonceq eu plantear qué es una dieta, qué significa equilibrada, y cuales son esas necesidades. Si no, es un ejercicio de llamarle a variables cosas, no de solución de problemas. A partir del objetivo, por *domain driven design*, se va evolucionando en la representación y abstracción y finalmente solución del problema.

2023-05-15 08:08 UTC, JJ commented on doc/Secciones/01_Introduccion.tex
> +    \item Diseñar e implementar un algoritmo que identifique y sustituya ingredientes en una receta según las intolerancias alimentarias del usuario y mantenga la coherencia de la receta.
1. Identificar claramente el problema y para quién quieres resolverlo. ¿Para personas en general con unos requisitos económicos? ¿Personas específicas con restricciones alimentarias médicas o morales? ¿Nutricionistas a los que les piden que se elabore una dieta? ¿Quieres generar recetas nuevas con restricciones? ¿Recetarios con tope de calorías o de proteínas? ¿Todos ellos?
2. Una vez que tengas claro el problema que quieres resolver, tienes que ver qué objetivos específicos quieres alcanzar, identificando cuales son dependientes unos de otros. Por ejemplo, si quieres crear dietas que maximicen o minimicen algo, habría que hacer eso antes o después que dietas en las que se suttituya un ingrediente por otro, y antes de dietas que tengas las dos cosas. 

El que trabajes con unos clientes u otros o con un problema u otro es elección tuya; en el TFG tienes que darte cuenta de cuales son las relaciones entre un problema y otro y como puedes secuenciar su solución, si es que es posible.

2023-05-18 15:42 UTC, Slowmybrosh commented
@JJ Cuando puedas échale un vistazo

2023-05-19 15:31 UTC, JJ requested changes
Iba a aprobar por no bloquear más, pero realmente no se puede avanzar si no hay al menos un objetivo claro y si no está claro cómo se formulan los objetivos y qué es un objetivo y qué tareas que se tienen que hacer para alcanzarlo (que, como tales tareas, se tienen que formular como problemas, no como cosas que hacer).

Dale una vuelta a la documentación que he pasado, pero en particular tienes que

1. Formular un problema y un cliente *claramente*. Hay *una* persona que quiere hacer *una cosa*. Lo que quiere hacer se describe en el *user journey*. Si es una persona que tiene restricciones alimentarias, y quiere adaptar las recetas, eso es tan válido como que sea un nutricionista que quiere diseñar dietas a medida para clientes. Pero tienes que aclarar desde el principio *cual de los dos es*.
2. Los objetivos siempre están en el espacio del problema: "Quiero crear, a petición de un usuario, *platos* adaptados a restricciones alimentarias.
3. Los problemas tienen que dejar claro el contexto. En el caso anterior, no tienes que diseñar platos a partir de complentes. Tienes que partir de un plato y aplicarle restricciones de la mejor forma posible, eliminando componentes o sustituyendo por otros que tengan un sabor parecido. Pero eso a la vez implica un subobjetivo: caracterizar ingredientes de forma que se pueda sustituir uno por otro. Y eso, a la vez, puede ser o muy simple o muy complicado. Simple (PMV): ponerlo uno a mano, o simplemente eliminar el componente. Complicado: hacer un algoritmo o un sistema de machine learning como los del paper que te enseñé.
4. También puede ser que uno simplemente quiera tener un recetario, pero en ese caso tendrás que plantear bien el problema: se quieren guardar los platos hechos con una puntuación, quieres buscar platos que ya hayas hecho con los ingredientes que tienes o con un mínimo de compra...

Yo optaría por esto último, porque es simple, no tienes que implementar algoritmos complejos, y realmente puede resolver un problema. También lo haría como aplicación móvil, para que se pueda usar fácilmente en la cocina. A partir de ahí, si tienes tiempo, puedes ponerle cosas más complejas: escanear tickets del supermercado, por ejemplo, pero yo no lo complicaría más.

En todo caso, volvemos a lo importante en esta fase:
1. Identificar un cliente/un problema
2. Escribir el user journey a partir del cual se identifica qué tipo de implementación hace falta.
3. Formular varios productos míniamente viables que sirvan como etapas sucesivas en un desarrollo

2023-05-19 15:31 UTC, JJ commented on doc/Secciones/01_Introduccion.tex
> +        \item Diseñar e implementar un algoritmo que genere dietas equilibradas basandose en las necesidades y características individuales del usuario.
También es una tarea, implícita si quieres alcanzar el objetivo.

2023-05-19 15:31 UTC, JJ commented on doc/Secciones/01_Introduccion.tex
> +        \item Implementar una función que permita a los usuarios reemplazar ingredientes problemáticos por alternativas adecuadas según sus alergias o intolerancias. Manteniendo una coherencia en la
No es parte del objetivo. Puede ser la solución al problema, pero tienes que formular el problema. Por otro lado, los objetivos (o subobjetivos) no pueden tener detalles como *una* función. Pueden ser una, muchas, o una forma de interaccionar, pero no puedes decirlo, tienes que irlo averiguando en el proceso de desarrollo.

2023-05-19 15:31 UTC, JJ commented on doc/Secciones/01_Introduccion.tex
> +    \item Implementar un sistema de gestión de usuarios que permita la creación, autenticación y autorización de usuarios en el software.
No es un objetivo, ni una tarea, ni algo que se deduzca automáticamente de la solución del problema. Tienes que formular si lo que quieres es solucionar un problema para una persona en su dispositivo personal, o hacer un servicio para muchas personas en la nube. El que hagas uno u otro depende del problema que quieras solucionar y para quien.

2023-05-19 15:31 UTC, JJ commented on doc/Secciones/01_Introduccion.tex
> +        \item Diseñar e implementar una base de datos de usuarios con sus respectivas credeniales e información personal.
Detalle de implementación, no es un objetivo, puede ser un PMV, pero no toca ponerlo aquí.

2023-05-19 15:31 UTC, JJ commented on doc/Secciones/01_Introduccion.tex
> +        \item Desarrollar un mecanismo de autenticación y autorización para garantizar la seguriadad y privacidad de los datos de los usuarios.
Exactamente igual que lo que he dicho antes. El proceso de desarrollo tiene que ser el que te ayude a decidir el producto y si va a ser personal, multiusuario, multi tenant, mismo producto para dietistas que para personas (o con parte de lógica de negocio compartida) o qué.

2023-05-19 15:31 UTC, JJ commented on doc/Secciones/02_Estado_del_arte.tex
> +Una aplicación quizá más conocida es \href{https://cookpad.com/es/home}{\emph{Cookpad}}, esta es una de las aplicaciones más descargadas de \emph{Apple Store} y \emph{Google Play} en la sección de co
:arrow_up:

2023-05-21 14:57 UTC, Slowmybrosh commented
@JJ He cambiado el problema siguiendo los consejos de los últimos comentarios, cambiando también los objetivos del proyecto, intentando que sean PMV. Cuando puedas échales un vistazo

2023-05-22 08:41 UTC, JJ requested changes
Los objetivos se parecen cada vez más a objetivos del proyecto, pero aparte de lo comentado puntualmente, convendría que crearas ya las historias de usuario en el repo y las enlazaras con el objetivo correspondiente. Cada objetivo debe ir encaminado a satisfacer una historia de usuario.

2023-05-22 08:41 UTC, JJ commented on doc/Secciones/01_Introduccion.tex
> +    \item Historial de recetas y sistema de calificación. Permitir a los usuarios guardar y calificar las recetas que han concinado junto con comentarios o modificaciones para facilitar los futuros u
Yo esto no lo veo ni un objetivo, ni veo que encaje con ningún user journey ni historia de usuario. Deberías afinar, por cierto, las historias de usuario antes de los objetivos.

2023-05-22 15:33 UTC, Slowmybrosh commented on doc/Secciones/01_Introduccion.tex
> +El usuario se entera de la aplicación móvil y la instala, posteriormente debe registrarse creando una nueva cuenta y la configura proporcionando datos relevantes como el tipo de dieta. En este punto,
Estoy haciendo todo lo que puedo intentando sacar adelante el proyecto, si te parece mejor nos vemos y concretamos todos los puntos. 

Sobre el registro del usuario, sirve para almacenar los datos del mismo e inicialmente, tener prevista una calificación y comentarios de la receta, para lo que se necesitaría una gestión de usuarios. Ya que ha cambiado el esquema del proyecto ya no es necesario una implementación basada en la nube más que una base de datos con recetas e ingredientes o algo similar. La parte de ingresar el inventario pienso que sería más cuestión de implementación. Y sobre el user journey, me estoy intentando poner en el POV de un usuario de la aplicación, ese es el que yo haría como usuario inicial. Y en futuras revisiones de la aplicación, sería posible implementar las funcionalidades adicionales que comentas.

2023-05-22 15:41 UTC, Slowmybrosh commented on doc/Secciones/01_Introduccion.tex
> +    \item Inclusión de preferencias dietéticas. Añadir la funcionalidad para que los usuarios puedan guardar sus restricciones dietéticas (intolerancias, alergias, preferencias) y mostrar solo receta
No solo lo especifico para personas con intolerancias dietéticas permanentes. Hay casos de personas intolerantes a un alimento que posteriormente pueden dejar de ser intolerantes. De la misma manera, está especificado para personas con una dieta concreta (vegana, vegetariana, etc...) que no son permanentes. Ese es el motivo que debe ir especificado en los detalles de implementación.

2023-05-22 16:15 UTC, JJ commented on doc/Secciones/01_Introduccion.tex
> +El usuario se entera de la aplicación móvil y la instala, posteriormente debe registrarse creando una nueva cuenta y la configura proporcionando datos relevantes como el tipo de dieta. En este punto,
Todos los miércoles voy a la Escuela, nos podemos ver a las 10.
Ahora mismo no puedes decir si vas a registrar al usuario o no y qué datos vas a almacenar. Todo lo que decidas tiene que ser para resolver problemas del usuario, registrados en sus historias de usuario. Los comentarios tampoco sirven a ninguna historia de usuario. En este punto del desarrollo, tienes que tener claro qué quieren los usuarios y nada más.

2023-05-22 16:18 UTC, JJ commented on doc/Secciones/01_Introduccion.tex
> +    \item Inclusión de preferencias dietéticas. Añadir la funcionalidad para que los usuarios puedan guardar sus restricciones dietéticas (intolerancias, alergias, preferencias) y mostrar solo receta
Pueden dejar de serlo, pero no en el momento en que busquen. La cuestión es que esto tiene que estar en una historia de usuario, no contestándome a revisiones que te haga. Y por eso tienes que tener las historias de usuario, el user journey y todo eso, antes que nada. El trabajo de *design thinking* https://www.linkedin.com/pulse/comenzando-con-un-trabajo-fin-de-gradom%C3%A1ster-%C3%A1gil-juan-j-merelo/?originalSubdomain=es es imprescindible para identificar claramente las necesidades de los usuarios, y partir de ellas para desarrollar algo que resuelva el problema, y no resuelva nada más que el problema (es decir, que no le añadas "comentarios" ni "puntuaciones" ni nada por el estilo)

2023-05-22 16:21 UTC, Slowmybrosh commented on doc/Secciones/01_Introduccion.tex
> +El usuario se entera de la aplicación móvil y la instala, posteriormente debe registrarse creando una nueva cuenta y la configura proporcionando datos relevantes como el tipo de dieta. En este punto,
Me parece bien, ¿Cuál era el despacho? 

Pero para una mayor coherencia para el usuario, si que debería estar registrado. Ya que ayudaría en diversos puntos, como en guardar recetas. Sería posible tener un fichero donde se guarden los identificadores de esas recetas, pero sería poco eficiente guardarlo de esta manera. En el caso de tener una base de datos con los usuarios, se podría almacenar una relación del usuario con la receta.

2023-05-22 16:27 UTC, JJ commented on doc/Secciones/01_Introduccion.tex
> +El usuario se entera de la aplicación móvil y la instala, posteriormente debe registrarse creando una nueva cuenta y la configura proporcionando datos relevantes como el tipo de dieta. En este punto,
2D34
De veras, no insistas en el registro. Para empezar, no es un objetivo, es una característica que formará parte de un producto mínimamente viable determinado, no sabemos cuál. Pero para continuar, es que no sabemos todavía el producto que vamos a desarrollar, ni qué dará tiempo a hacer. Insisstir en una característica determinada, registro, que a su vez causará una serie de problemas (¿las recetas tienen propietario? ¿Te puedes registrar con usuario de Google?) y que no es trivial implementar (¿cómo te aseguras que la información de un usuario no la puedan ver los otros?) es *muy* prematuro. 
Es esencial centrarse en el problema del usuario y en la lógica de negocio. A partir de ahí, temas de interacción de usuario y de despliegue y arquitectura de la aplicación ya se irán viendo.

2023-05-22 18:04 UTC, Slowmybrosh commented
@JJ He creado las historias de usuario relativas a la resolución del problema del proyecto, cambiado el user journey intentando eliminar cualquier detalle de implementación y corregido los objetivos para reflejar el proceso de desarrollo de la solución al problema del proyecto eliminando también los posibles detalles de implementación

2023-05-29 07:29 UTC, JJ requested changes
Estás un poco más cerca al reducir un poco lo que quieres hacer, pero en esta etapa lo más importante es convertir eso que quieres hacer en objetivos que representen problemas que tenga el usuario.

2023-05-29 07:29 UTC, JJ commented on doc/Secciones/01_Introduccion.tex
> +Cualquier persona sabe qué es una dieta, ya que todos nos alimentamos cada día. La palabra ``dieta' se refiere al conjunto de alimentos que ingerimos. Sin embargo, no todo el mundo lleva una dieta eq
Las comillas tendrás que corregirlas.

2023-05-29 07:29 UTC, JJ commented on doc/Secciones/01_Introduccion.tex
> +    \item Introducir ingredientes en la despensa. El usuario debe poder introducir los ingredientes que tiene en la despensa para utilizarlos en la búsqueda de recetas.
Agh, no. ¿Cómo va a ser un objetivo algo que tiene que hacer el usuario porque tú lo obligas?

2023-05-29 07:29 UTC, JJ commented on doc/Secciones/01_Introduccion.tex
> +    \item Busqueda básica de recetas. El usuario debe ser capaz de buscar recetas utilizando los ingredientes que desee.
Los objetivos están siempre en el dominio del problema. El objetivo no puede ser "búsqueda", el objetivo es que el usuario encuentre. No "debe ser capaz de buscar" sino "debe encontrar". 
Los objetivos como te he comentado son sumamente importantes, y tienes que convertirlos en tu cabeza en posibles tests unitarios o de otro tipo. ¿En qué test se convertiría "búsqueda básica"? ¿En la existencia de un formulario que con un botón que diga "búsqueda básica"? "Encontrar", por el contrario, *sí* dice que el objetivo es proporcionar al usuario lo que busca.

2023-05-29 07:29 UTC, JJ commented on doc/Secciones/01_Introduccion.tex
> +    \item Inclusión de preferencias dietéticas. Añadir la funcionalidad para que los usuarios puedan encontrar recetas aptas para su consumo teniendo en cuenta sus restricciones alimentarias (intoler
¿Has visto si hay alguna forma de convertir "añadir la funcionalidad" en un objetivo *que esté en el dominio del problema*? ¿Qué objetivo quieres superar incluyendo las preferencias dietéticas?

2023-05-29 07:29 UTC, JJ commented on doc/Secciones/01_Introduccion.tex
> +        \item Sustitución de ingredientes. Implementar una característica que permita sugerir sustituciones adecuadas para los ingredientes faltantes en una receta, teniendo en cuenta las restriccion
Una vez más, ¿podrías convertir esto en algo que esté en el dominio del problema? ¿Qué objetivo se quiere superar sustituyendo los ingredientes?

2023-05-29 16:41 UTC, Slowmybrosh commented on doc/Secciones/01_Introduccion.tex
> +        \item Sustitución de ingredientes. Implementar una característica que permita sugerir sustituciones adecuadas para los ingredientes faltantes en una receta, teniendo en cuenta las restriccion
Esto estaría en el dominio del problema?

"El usuario debe ser capaz de sustituir ingredientes en la receta por uno similar. Ya sea por la falta de dicho ingrediente o porque su alimentación le impide consumirlo."

2023-05-29 16:42 UTC, Slowmybrosh commented on doc/Secciones/01_Introduccion.tex
> +Cualquier persona sabe qué es una dieta, ya que todos nos alimentamos cada día. La palabra ``dieta' se refiere al conjunto de alimentos que ingerimos. Sin embargo, no todo el mundo lleva una dieta eq
Sí, me di cuenta en el último commit que las comillas estaban mal puestas, con la siguiente corrección cambiaré eso.

2023-05-29 16:47 UTC, JJ commented on doc/Secciones/01_Introduccion.tex
> +        \item Sustitución de ingredientes. Implementar una característica que permita sugerir sustituciones adecuadas para los ingredientes faltantes en una receta, teniendo en cuenta las restriccion
El usuario no va a hacerlo, serás tú con tu programa.
Es esencial que entiendas lo que quiere el usuario. ¿Por qué quiere sustituir ingredientes? ¿No tiene suficiente con recetas que no lo usen?
En design thinking una parte esencial es empatizar con el usuario, entender qué es lo que quiere. Si no lo sabes, no podrás decidir si la sustitución es válida. Suponte que tu algoritmo sustituye la sal por una pera. O las peras por garbanzos. ¿Qué es lo que quiere sustituir y por qué?

2023-05-29 16:55 UTC, Slowmybrosh commented on doc/Secciones/01_Introduccion.tex
> +        \item Sustitución de ingredientes. Implementar una característica que permita sugerir sustituciones adecuadas para los ingredientes faltantes en una receta, teniendo en cuenta las restriccion
El usuario querrá sustituir ingredientes para poder elegir la receta que quiera dentro de cierto criterio. Por ejemplo, si quiere macarrones con tomate pero no tiene tomate, se deberá sustituir por otra salsa que si pueda hacer. Permitiendo que sus comidas no estén limitadas por una lista de recetas que pueda hacer solo con los ingredientes de los que disponga.

2023-05-29 17:05 UTC, JJ commented on doc/Secciones/01_Introduccion.tex
> +        \item Sustitución de ingredientes. Implementar una característica que permita sugerir sustituciones adecuadas para los ingredientes faltantes en una receta, teniendo en cuenta las restriccion
No quiero que pierdas mucho el tiempo con esto, Alejandro. Es un problema complejo y no merece la pena que le demos vueltas. En general, cuando sustituyes un ingrediente por otro buscas las diferentes dimensiones que un ingrediente le da al plato: sabor (en las 6 o 7 dimensiones del sabor, no sé cómo andan ahora), textura, o cualquier cosa por el estilo. Y para eso tienes que hacer un estudio bastante complejo del papel que ocupa cada ingrediente en un plato y en todas esas dimensiones.
Pero lo que quiero que aprendas con ese ejercicio es que tienes siempre que pensar desde el punto de vista del usuario. Un usuario quiere sustituir un ingrediente, y no simplemente buscar platos sin ese ingrediente, por algo. En el trabajo que te he mencionado varias veces se trataba de un chef, por ejemplo: quiere ofrecer a sus clientes con algún tipo de restricción platos con un sabor (y supongo que textura) similares. Una persona normal le dará igual hacer las cosas sin salsa de tomate, simplemente buscará platos que no la incluyan. Por eso tienes que empatizar, porque si no lo haces no puedes resolver su problema.
Para que veas que no es tan simple lo que dices, estás diciendo que quiere sustituirlo por otra salsa. Pero para eso tienes que dividir los ingredientes de un plato en recetas más simples, y también tener toda una clasificación tipo salsas, bechameles, y cosas por el estilo. Ya de por sí no es fácil. Pero si quieres incluirlo, la cuestión es que tienes que 
1. Ponerlo todo desde el punto de vista del usuario: quiere *evitar la monotonía*/*crear nuevos platos en un restaurante*/*acaba de tener la restricción alimentaria y quiere seguir experimentando los mismos sabores*
2. Examinar el dominio del problema para ver realmente qué es lo que se busca. Por ejemplo, un chef va a buscar sustitución de recetas simples para crear otras más complejas: sofritos, fumés... Una persona que quiera buscar los mismos sabores tratará de sustituir ingredientes (y en muchos casos no se podrá, por ejemplo, ajo -> cebollino es parecido, pero no es lo mismo)

2023-05-29 17:07 UTC, JJ commented on doc/Secciones/01_Introduccion.tex
> +        \item Sustitución de ingredientes. Implementar una característica que permita sugerir sustituciones adecuadas para los ingredientes faltantes en una receta, teniendo en cuenta las restriccion
En todo caso, si no tienes una idea más o menos clara de qué es lo que implica una historia de usuario, simplemente exclúyela. Siempre puedes ponerla como trabajo futuro.

2023-05-29 17:30 UTC, Slowmybrosh commented on doc/Secciones/01_Introduccion.tex
> +        \item Sustitución de ingredientes. Implementar una característica que permita sugerir sustituciones adecuadas para los ingredientes faltantes en una receta, teniendo en cuenta las restriccion
Entonces quito ese objetivo completamente y dejo solo el de encontrar recetas?

2023-05-29 17:43 UTC, JJ commented on doc/Secciones/01_Introduccion.tex
> +        \item Sustitución de ingredientes. Implementar una característica que permita sugerir sustituciones adecuadas para los ingredientes faltantes en una receta, teniendo en cuenta las restriccion
Esa es una decisión que tienes que tomar tú en función de lo que quieras hacer. Lo único que digo es que si lo dejas, tiene que tener una serie de características.

2023-05-29 17:45 UTC, Slowmybrosh commented on doc/Secciones/01_Introduccion.tex
> +        \item Sustitución de ingredientes. Implementar una característica que permita sugerir sustituciones adecuadas para los ingredientes faltantes en una receta, teniendo en cuenta las restriccion
Lo voy a quitar y lo dejaré como un milestone al que es posible que se llegue en un futuro, o no.

2023-05-30 09:20 UTC, Slowmybrosh commented
@JJ

2023-05-30 09:58 UTC, JJ requested changes
no pongo ninguna objeción a los objetivos, pero deberías asegurarte de revisar todos los comentarios que se hacen; hay un par desde un par de rondas que no has mirado.

2023-05-30 09:58 UTC, JJ commented on doc/Secciones/01_Introduccion.tex
> +En este capítulo se describirá la motivación y los objetivos principales del proyecto.
Esto sigues sin cambiarlo. Por favor, comprueba en adelante que cambias todos los comentarios que se hacen.

2023-05-30 09:58 UTC, JJ commented on doc/Secciones/02_Estado_del_arte.tex
> +Una aplicación quizá más conocida es \href{https://cookpad.com/es/home}{\emph{Cookpad}}, esta es una de las aplicaciones más descargadas de \emph{Apple Store} y \emph{Google Play} en la sección de co
:arrow_up:

2023-05-30 09:58 UTC, JJ commented on doc/proyecto.tex
> +%\bibliography{bibliografia.bib}\addcontentsline{toc}{chapter}{Bibliografía}
Esto es un comentario, ¿por qué lo cambias?

2023-05-30 14:22 UTC, Slowmybrosh commented on doc/Secciones/01_Introduccion.tex
> +En este capítulo se describirá la motivación y los objetivos principales del proyecto.
Aquí que es lo que debería poner como introducción al capítulo?

2023-05-30 14:25 UTC, Slowmybrosh commented on doc/proyecto.tex
> +%\bibliography{bibliografia.bib}\addcontentsline{toc}{chapter}{Bibliografía}
Estaría probando para ver el capítulo con la bibliografía en el pdf y lo subiría así sin querer

2023-05-31 17:28 UTC, Slowmybrosh commented on doc/Secciones/02_Estado_del_arte.tex
> +Una aplicación quizá más conocida es \href{https://cookpad.com/es/home}{\emph{Cookpad}}, esta es una de las aplicaciones más descargadas de \emph{Apple Store} y \emph{Google Play} en la sección de co
Inicialmente no, por ahora se trata de un recetario. Tengo que cambiar todo el estado del arte?

2023-06-01 11:15 UTC, JJ commented on doc/Secciones/02_Estado_del_arte.tex
> +Una aplicación quizá más conocida es \href{https://cookpad.com/es/home}{\emph{Cookpad}}, esta es una de las aplicaciones más descargadas de \emph{Apple Store} y \emph{Google Play} en la sección de co
Tienes que eliminar lo que no tenga que ver con tu objetivo.

2023-06-01 11:17 UTC, JJ commented on doc/proyecto.tex
> +%\bibliography{bibliografia.bib}\addcontentsline{toc}{chapter}{Bibliografía}
Piensa que más cambios osn más cosas a revisar... si lo has hecho por equivocación, déjalo como estaba.

2023-06-01 15:52 UTC, Slowmybrosh commented
@JJ He creado los issues correspondientes a los capítulos que avanzan #8. 

En el capítulo de estado del arte he cambiado alguna cosa, pero como las aplicaciones que se mencionan también se usan como recetario he optado por dejarlas. Añadiendo una línea al final sobre el objetivo del software a desarrollar. 

Sobre el fichero "proyecto.tex" arreglé los cambios que hice sin darme cuenta

2023-06-01 15:55 UTC, JJ approved these changes
Por favor, elimina del estado del arte lo que no tenga que ver. No voy a bloquear la aprobación por eso, pero *hazlo*

2023-06-01 16:03 UTC, Slowmybrosh commented
> Por favor, elimina del estado del arte lo que no tenga que ver. No voy a bloquear la aprobación por eso, pero _hazlo_

Qué consideras que no tiene que ver con el estado del arte?

2023-06-01 16:05 UTC, JJ commented
> > Por favor, elimina del estado del arte lo que no tenga que ver. No voy a bloquear la aprobación por eso, pero _hazlo_
> 
> Qué consideras que no tiene que ver con el estado del arte?

El cookpad, por ejemplo, que es donde está el comentario. Es una red social basada en fotos de recetas, por lo que he entendido. Quizás alguna más, pero esa es donde he comentado.

2023-06-01 16:13 UTC, Slowmybrosh commented
> > > Por favor, elimina del estado del arte lo que no tenga que ver. No voy a bloquear la aprobación por eso, pero _hazlo_
> > 
> > 
> > Qué consideras que no tiene que ver con el estado del arte?
> 
> El cookpad, por ejemplo, que es donde está el comentario. Es una red social basada en fotos de recetas, por lo que he entendido. Quizás alguna más, pero esa es donde he comentado.

Yo si ves que no es relevante lo quito pero es un recetario creado por la comunidad. Donde suben recetas completas (con ingredientes y pasos) con sus fotos, las comentan, etc... Pero por las veces que la he usado, funciona como un recetario normal donde encontrar cualquier tipo de receta

2023-06-01 16:20 UTC, JJ commented
@Slowmybrosh OK, lo que veas. Si no te sirve el comentario, ciérralo de todas formas con "resuelto" y diciendo por qué lo haces.

2023-06-01 16:27 UTC, Slowmybrosh commented on doc/Secciones/02_Estado_del_arte.tex
> +Una aplicación quizá más conocida es \href{https://cookpad.com/es/home}{\emph{Cookpad}}, esta es una de las aplicaciones más descargadas de \emph{Apple Store} y \emph{Google Play} en la sección de co
Cookpad es un recetario online compuesto de las recetas que suben los usuarios para otros usuarios, así que estimo oportuno incluirlo en el estado del arte actual.

2023-06-01 16:28 UTC, Slowmybrosh commented
@JJ Una vez cerrados todos los comentarios, puedo hacer el merge?

2023-06-02 05:59 UTC, JJ commented
> @JJ Una vez cerrados todos los comentarios, puedo hacer el merge?

Está ya aprobado, así que cuando quieras

2023-06-02 15:14 UTC, merged