Metodologia - Documentación
Slowmybrosh/TFG-DietPlanner pull request #25
Opened 2023-06-04 11:11 UTC by Slowmybrosh

Nuevos cambios en la documentación: 
- Se ha especificado la metodología a seguir (#15). Añadiendo: Marco ágil, User Journeys, planificación e impacto de github en la metodología.
- Se han añadido los user journeys (#16) a la metodología.
- Se avanza (#8) añadiendo a la documentación la descripción de la metodología.

2023-06-05 06:36 UTC, JJ requested changes
Una pequeña reorganización y atención a detalles vendría bien.

2023-06-05 06:36 UTC, JJ commented on doc/Secciones/03_Metodologia.tex
> +En este capítulo se describirá la metodología utilizada en el desarrollo a lo largo del proyecto.
La introducción debe incluir un pequeño resumen de lo que viene a continuación y por qué.

2023-06-05 06:36 UTC, JJ commented on doc/Secciones/03_Metodologia.tex
> +Debido a las limitaciones de la gestión de proyectos, a finales de los 90 se empezó a utilizar una metodología ágil. Pero no fue hasta 2001 que un grupo de expertos desarrolla el ``Manifiesto por el
¿Qué principios vas a aplicar tú aquí? 
También pon una cita o enlace.

2023-06-05 06:36 UTC, JJ commented on doc/Secciones/03_Metodologia.tex
> +Este proyecto se centrará en el uso de la metodología \emph{Scrum}'. Que es uno de los modelos más utilizados actualmente en el desarrollo de software. Este divide el trabajo en ``Sprints'', interval
No vas a usar Scrum porque lo estás haciendo tú solo. Kanban también tiene sprints.

2023-06-05 06:36 UTC, JJ commented on doc/Secciones/03_Metodologia.tex
> +\section{User Journeys}
La maldición De las Mayúsculas arbitrarias

2023-06-05 06:36 UTC, JJ commented on doc/Secciones/03_Metodologia.tex
> +En primer lugar se enfocará el software a un estudiante que cuenta con un presupuesto ajustado al mes y no puede permitirse el lujo de comprar en el supermercado todos los días. Dicho estudiante se s
"se enfocará el software" ¿No sería mejor trataremos de resolver el problema de?

2023-06-05 06:36 UTC, JJ commented on doc/Secciones/03_Metodologia.tex
> +Otro tipo de usuario al que se orienta este software es una persona mayor que no se encuentra en disposición de ir al supermercado cada vez que le faltan ingredientes y tiene una despensa limitada. D
Deberías contarlo como problemas, no como "tipos de usuario". Eso son las historias de usuario.

2023-06-05 06:36 UTC, JJ commented on doc/Secciones/03_Metodologia.tex
> +\subsection{Encontrar recetas}
Debes explicar que usas milestones y los productos mínimamente viables que vas a obtener.

2023-06-05 06:36 UTC, JJ commented on doc/Secciones/03_Metodologia.tex
> +\section{Github}
No puedes titular una sección con el resultado de una decisión. Debes decir qué parte de la planificación es esta y qué es lo que quieres resolver. En todo caso, GitHub sería anterior a la planificación, puesto que estás usando milestones en GitHub.

2023-06-05 06:36 UTC, JJ commented on doc/Secciones/03_Metodologia.tex
> +\emph{Github} es una herramienta de control de versiones que permite hacer uso de \emph{issues} y \emph{milestones}. Permitiendo llevar tanto los registros de los diferentes cambios que se hacen en e
Los milestones *son* la planificación, no son cosas de GitHub.

2023-06-05 15:57 UTC, Slowmybrosh commented on doc/Secciones/03_Metodologia.tex
> +\section{User Journeys}
Si, se me coló esa mayúscula. Corrijo la errata en los próximos cambios

2023-06-06 10:49 UTC, JJ requested changes
Va mejorando, pero todavía habría que darle una vuelta.

2023-06-06 10:49 UTC, JJ commented on doc/Secciones/03_Metodologia.tex
> +    \item Autogestión de los equipos
Algunas que no se apliquen demasiado bien, como estas, es mejor que las elimines. O la apliques a tu caso, indicando que estás desarrollando autónomamente el proyecto, en vez de hacer un "mandao" como muchos otros TFGs.

2023-06-06 10:49 UTC, JJ commented on doc/Secciones/03_Metodologia.tex
> +Si bien es cierto, en este tipo de proyecto donde solo está trabajando una persona desarrollando un software por cuenta ``propia'', hay ciertas claves que no coinciden con la metodología a seguir. Po
"Si bien es cierto" va siempre seguido de "que"

2023-06-06 10:49 UTC, JJ commented on doc/Secciones/03_Metodologia.tex
> +Este proyecto se centrará en el uso de la metodología \emph{Scrum}'. Que es uno de los modelos más utilizados actualmente en el desarrollo de software. Este divide el trabajo en ``sprints'', interval
"Que" nunca sigue a un punto. Y lo que comentas no es Scrum, que es precisamente el tema en el que más expertos (reales o imaginarios) te vas a encontrar en #8 . Scrum es una reunión con unas reglas definidas, dirigida por un Scrum master. Los sprints son más o menos inherentes al desarrollo ágil, pero tienes que poner explícitamente a qué corresponden en tu caso (¿milestones? ¿PRs?)

2023-06-06 18:32 UTC, Slowmybrosh commented on doc/Secciones/03_Metodologia.tex
> +    \item Autogestión de los equipos
Se han dejado exclusivamente las claves relativas al proyecto

2023-06-06 18:38 UTC, Slowmybrosh commented
@JJ He hecho algunos cambios:
- Se ha corregido la sección del marco ágil, dejando exclusivamente las claves relativas al proyecto y eliminando la referencia a usar una metodología concreta. 
- Se corrige la sección de github, describiendo el impacto de git en la metodología
- Se ha especificado el uso de milestones en la planificación del proyecto

2023-06-07 06:44 UTC, JJ approved these changes
Algunos cambios de detalle, pero en general adelante.

2023-06-07 06:44 UTC, JJ commented on doc/Secciones/03_Metodologia.tex
> +\section{User Journeys}
¿Por qué no en este?

2023-06-07 06:44 UTC, JJ commented on doc/Secciones/03_Metodologia.tex
> +\subsection{Encontrar recetas}
Deberías poner como prefijo o algo de qué va: es un milestone, PMV o lo que sea.

2023-06-07 12:22 UTC, Slowmybrosh commented on doc/Secciones/03_Metodologia.tex
> +\section{User Journeys}
Me refería a los siguientes cambios de este PR, no al próximo. De todas maneras lo estoy arreglando de cara a corregir los fallitos mencionados antes de hacer el merge.

2023-06-07 12:25 UTC, Slowmybrosh commented on doc/Secciones/03_Metodologia.tex
> +\subsection{Encontrar recetas}
Esto se refiere a que en el título de la subsección ponga si es un milestone, pmv, etc...?

2023-06-12 08:41 UTC, merged