Diseño del proyecto
Slowmybrosh/TFG-DietPlanner pull request #35
Opened 2023-06-18 08:52 UTC by Slowmybrosh

Nuevos cambios:
- Se avanza #8 añadiendo un capítulo de diseño del proyecto.
- Se completa #34. En este capítulo se ha añadido el análisis de requisitos y un análisis funcional que incluye la descripción de casos de uso, diagrama UML del proyecto y diagramas de secuencia para los casos de uso.

2023-06-18 08:53 UTC, Slowmybrosh commented
@JJ Cuando puedas échale un vistazo a esto para cambiar lo que haga falta :)

2023-06-19 11:44 UTC, JJ commented
Rara vez se avanza directamente una HU, siempre son issues.

2023-06-19 11:46 UTC, JJ requested changes
Como te he comentado, los requisitos están totalmente en contra del desarrollo ágil, que se basa en crear productos y recibir retroalimentación del cliente. Los datos los vas desarrollando sobre la marcha, y el diagrama UML sólo tiene sentido a posteriori, cuando se ha terminado el desarrollo de una parte, para entender mejor la estructura del proyecto.

2023-06-19 11:46 UTC, JJ commented on doc/Secciones/04_diseño.tex
> +\section{Análisis de Requisitos}
Cuidado con las mayúsculas Arbitrarias.

2023-06-19 11:46 UTC, JJ commented on doc/Secciones/04_diseño.tex
> +Es fundamental definir una serie de requerimientos en el proyecto, ya que esto establece las bases y necesidades o expectativas que debe cumplir el sistema a desarrollar. En esta sección se analizará
Si usas desarrollo ágil, los únicos requisitos son los no funcionales, y en todo caso son características que tienes que sacar de las historias de usuario y poner en los milestones.

2023-06-19 17:07 UTC, JJ commented
> > Como te he comentado, los requisitos están totalmente en contra del desarrollo ágil, que se basa en crear productos y recibir retroalimentación del cliente. Los datos los vas desarrollando sobre la marcha, y el diagrama UML sólo tiene sentido a posteriori, cuando se ha terminado el desarrollo de una parte, para entender mejor la estructura del proyecto.
> 
> ¿Los diagramas de las funciones y los casos de uso tendría que corregir también? Si es así, necesitaría una pequeña orientación sobre que poner en este capítulo? porque me estoy agobiando un poco y mi intención es terminarlo en Julio

¿Corregir? ¿Te sirven para algo? Si no tienes historias de usuario, ¿cómo vas a tener casos de uso? ¿Cómo vas a tener diagramas?

Si vas a usar desarrollo ágil, tienes que usarlo desde el principio, y por supuesto contar qué es lo que vas a usar. Realmente crear diagramas y requisitos sin ninguna relación con el usuario (porque, sin historias de usuario, no sabemos lo que quiere el usuario) no creo que sea ni ágil ni una buena forma de emplear el tiempo de desarrollo.

2023-06-28 14:10 UTC, closed without merging