Implementacion
Slowmybrosh/TFG-DietPlanner pull request #39
Opened 2023-06-21 15:38 UTC by Slowmybrosh

Para una correcta documentación (#8), se necesitan justificar todas las decisiones tomadas en el desarrollo del proyecto (#33).
Inicialmente, en este capítulo se han añadido los siguientes apartados: 
- Uso de Github
- Plataforma de la aplicación
- Lenguaje de programación ajustado a la plataforma

2023-06-22 15:14 UTC, Slowmybrosh commented
@JJ Cuando puedas le echas un vistazo a este capítulo?

2023-06-22 17:46 UTC, JJ requested changes
Creo que este PR tiene contenido que es prematuro o mezcla cosas que no son relevantes. Convendría que te lo replantearas, o que lo dejaras aparcado hasta que el avance del proyecto lo requiera.

2023-06-22 17:46 UTC, JJ commented on doc/Secciones/04_Implementacion.tex
> +\section{Framework}
Me parece muy prematuro que expliques esto, mucho antes de saber los requisitos que vas a necesitar en la plataforma o el lenguaje.

2023-06-22 17:46 UTC, JJ commented on doc/Secciones/04_Implementacion.tex
> +    \item Angular
Estás mezclando frameworks de tipo muy diferente, y poniendo sólo unos pocos. En general, la utilidad de esto es bastante discutible.

2023-06-22 17:46 UTC, JJ commented on doc/Secciones/04_Implementacion.tex
> +En todo proyecto actual, se utiliza alguna herramienta que permite gestionar las versiones del código y colaborar en la construcción del mismo. Existen numerosas utilidades que lo facilitan, como \em
BitBucket y demás no son herramientas, son sitios de trabajo en grupo que usan preferentemente una herramienta. Tampoco entiendo muy bien ni el orden en que lo explicas (después de los frameworks) ni la extensión que le das.

2023-06-22 17:46 UTC, JJ commented on doc/Secciones/04_Implementacion.tex
> +GitLab se define como ``Una plataforma completa para DevOps''. Cuenta tanto con una versión gratuita como dos planes adicionales enfocados a empresas. La suscripción ``Premium'' incluye ramas protegi
La utilidad de esto para tu proyecto y para #8 es muy discutible, ya que no lo vas a usar.

2023-06-22 17:46 UTC, JJ commented on doc/Secciones/04_Implementacion.tex
> +\section{¿Qué se considera ingrediente?}
Estás mezclando temas de diseño con temas relacionados con el estado del arte, y metiéndolo todo en "implementación". Todo ello, sin hacer realmente la implementación. Puedes organizarte como quieras, pero el objetivo de este capítulo es ir explicando las decisiones técnicas que tomes para #8 , no meter contenido sin mucha relación con el proyecto.

2023-06-22 17:46 UTC, JJ commented on doc/Secciones/04_Implementacion.tex
> +Se considerará que todo usuario cuenta en su cocina con:
Esto son decisiones que tienen que estar en el código primero, y probablemente sólo en el código. No las debes incluir en la memoria hasta que no hayas escrito el código correspondiente.

2023-06-23 08:54 UTC, Slowmybrosh commented on doc/Secciones/04_Implementacion.tex
> +\section{Framework}
Vale, lo quitaré hasta que haga falta afinarlo, si es que es necesario un framework para la plataforma

2023-06-23 08:55 UTC, Slowmybrosh commented on doc/Secciones/04_Implementacion.tex
> +    \item Angular
Haré en primer lugar un pequeño análisis de requisitos para ver en que lenguaje se desarrollará el backend de la aplicación y posteriormente un estudio de los framework disponibles

2023-06-23 08:59 UTC, Slowmybrosh commented on doc/Secciones/04_Implementacion.tex
> +En todo proyecto actual, se utiliza alguna herramienta que permite gestionar las versiones del código y colaborar en la construcción del mismo. Existen numerosas utilidades que lo facilitan, como \em
Dejaré la justificación de la elección de Github simplemente. La extensión era por justificar las ventajas y desventajas de cada "herramienta". También cambiaré el orden de las secciones para dotarlas de mayor sentido.

2023-06-23 09:02 UTC, Slowmybrosh commented on doc/Secciones/04_Implementacion.tex
> +\section{¿Qué se considera ingrediente?}
Se eliminará esta sección y se reflejará en el código solamente.

2023-06-23 10:31 UTC, Slowmybrosh commented
@JJ He quitado las cosas prematuras o irrelevantes, añadido un minusculo parrafo de porque se utiliza github. Además de elegir una justificación del lenguaje para la plataforma, teniendo en cuenta unos pequeños requisitos.

2023-06-23 10:34 UTC, JJ commented
Estás haciendo un PR para un issue en el que te comenté [esto](https://github.com/Slowmybrosh/TFG-DietPlanner/issues/33#issuecomment-1597482533). Sin un problema claramente planteado, es difícil evaluar si lo hecho resuelve el problema o no.

2023-06-23 10:37 UTC, Slowmybrosh commented
> Estás haciendo un PR para un issue en el que te comenté [esto](https://github.com/Slowmybrosh/TFG-DietPlanner/issues/33#issuecomment-1597482533). Sin un problema claramente planteado, es difícil evaluar si lo hecho resuelve el problema o no.

Debería tener creado un issue que plantee el problema de que lenguaje de programación elegir? Antes de incluir la respuesta en la documentación?

2023-06-23 10:38 UTC, JJ requested changes
Una vez más, no debes documentar lo que has elegido hasta que efectivamente lo hayas hecho en la fase de desarrollo del producto en la que estés. Todavía no has empezado a tirar las líneas de código, así que todavía no puedes hablar del lenguaje elegido. Tampoco sabes qué vas a hacer una vez lleges al nivel de abstracción del API, así que no lo hagas.
En general, te repito lo mismo que antes: cuando implementes documéntalo y documentar significa explicar los retos que has tenido para tomar una decisión y lo que has considerado.

2023-06-23 10:38 UTC, JJ commented on doc/Secciones/04_Implementacion.tex
> +La ventaja que decanta la decisión de elegir una plataforma web antes que una móvil se basa en que al usuario le será más sencillo utilizarla. Sin tener que descargar nada. Simplemente entrando a la
Aquí tendrás que especificar claramente cómo se adaptaría a los diferentes tipos de usuarios de las HU creadas

2023-06-23 10:38 UTC, JJ commented on doc/Secciones/04_Implementacion.tex
> +    \item Escalabilidad. Debe ser capaz de manejar el rendimiento requeridos por la plataforma. Teniendo en cuenta la velocidad de desarrollo y el rendimiento del mismo.
ESto no funcionaba en IV, no va a funcionar aquí.

2023-06-23 10:39 UTC, JJ commented on doc/Secciones/04_Implementacion.tex
> +Java es un lenguaje, creado con el objetivo de poder ser usado en cualquier lugar. Con independencia de la plataforma o hardware en el que se ejecutase. Debido a su gran comunidad de usuarios, tiene
Y por supuesto, tienes que evitar hacer afirmaciones muy discutibles, sin ninguna cita, que provoquen el rechazo de #8 sin ninguna ganancia a cambio.

2023-06-23 10:45 UTC, Slowmybrosh commented
> Una vez más, no debes documentar lo que has elegido hasta que efectivamente lo hayas hecho en la fase de desarrollo del producto en la que estés. Todavía no has empezado a tirar las líneas de código, así que todavía no puedes hablar del lenguaje elegido. Tampoco sabes qué vas a hacer una vez lleges al nivel de abstracción del API, así que no lo hagas. En general, te repito lo mismo que antes: cuando implementes documéntalo y documentar significa explicar los retos que has tenido para tomar una decisión y lo que has considerado.

Pero como empiezo a desarrollar las líneas de código para #22 si no tengo una plataforma elegida ni un lenguaje de programación

2023-06-23 10:46 UTC, JJ commented
> > Estás haciendo un PR para un issue en el que te comenté [esto](https://github.com/Slowmybrosh/TFG-DietPlanner/issues/33#issuecomment-1597482533). Sin un problema claramente planteado, es difícil evaluar si lo hecho resuelve el problema o no.
> 
> Debería tener creado un issue que plantee el problema de que lenguaje de programación elegir? Antes de incluir la respuesta en la documentación?

Deberías
1. No poner en la documentación cosas que no has hecho todavía en el proyecto. Elegir cosas es comenzar a usarlas, y luego justificar en la documentación qué pasos se han seguido para tomar la decisión, qué se ha considerado, y por qué.
2. Crear issue que planteen problemas específicos, con soluciones específicas. "Implementación" no es un problema.
3. En general, y salvo los primeros capítulos, va a haber muy pocos issues que estén relacionados sólo con #8. Los issues son para resolver problemas de los usuarios, y #8 sirve más bien para decidir cómo se formula o qué se incluye o no en la documentación.

Conviene en todo caso que sigas una metodología un poco más sistemática para abordar el proyecto. Primero tienes que plantear la motivación, escribir los user journey, usar design thinking y la metodología de "personas" para pefilar los usuarios, crear a continuación las historias de usuario, y sobre todo, documentar todo en el primer o primeros capítulos de la memoria antes de pasar a hacer la implementación, porque esos son los pasos para los proyectos. Ya te lo puse en el issue #36, y ni siquiera le has asignado un milestone. Convendría que fueras un poco sistemático para poder llevar el proyecto a buen término.

2023-06-23 10:51 UTC, Slowmybrosh commented
> > > Estás haciendo un PR para un issue en el que te comenté [esto](https://github.com/Slowmybrosh/TFG-DietPlanner/issues/33#issuecomment-1597482533). Sin un problema claramente planteado, es difícil evaluar si lo hecho resuelve el problema o no.
> > 
> > 
> > Debería tener creado un issue que plantee el problema de que lenguaje de programación elegir? Antes de incluir la respuesta en la documentación?
> 
> Deberías
> 
> 1. No poner en la documentación cosas que no has hecho todavía en el proyecto. Elegir cosas es comenzar a usarlas, y luego justificar en la documentación qué pasos se han seguido para tomar la decisión, qué se ha considerado, y por qué.
> 2. Crear issue que planteen problemas específicos, con soluciones específicas. "Implementación" no es un problema.
> 3. En general, y salvo los primeros capítulos, va a haber muy pocos issues que estén relacionados sólo con [[HU00] Miembro del tribunal - Criterios de Evaluación #8](https://github.com/Slowmybrosh/TFG-DietPlanner/issues/8). Los issues son para resolver problemas de los usuarios, y [[HU00] Miembro del tribunal - Criterios de Evaluación #8](https://github.com/Slowmybrosh/TFG-DietPlanner/issues/8) sirve más bien para decidir cómo se formula o qué se incluye o no en la documentación.
> 
> Conviene en todo caso que sigas una metodología un poco más sistemática para abordar el proyecto. Primero tienes que plantear la motivación, escribir los user journey, usar design thinking y la metodología de "personas" para pefilar los usuarios, crear a continuación las historias de usuario, y sobre todo, documentar todo en el primer o primeros capítulos de la memoria antes de pasar a hacer la implementación, porque esos son los pasos para los proyectos. Ya te lo puse en el issue #36, y ni siquiera le has asignado un milestone. Convendría que fueras un poco sistemático para poder llevar el proyecto a buen término.

Tengo lo relativo a #36 escrito en mi documentación local, pero no subido al proyecto.

2023-06-23 10:51 UTC, JJ commented
> > Una vez más, no debes documentar lo que has elegido hasta que efectivamente lo hayas hecho en la fase de desarrollo del producto en la que estés. Todavía no has empezado a tirar las líneas de código, así que todavía no puedes hablar del lenguaje elegido. Tampoco sabes qué vas a hacer una vez lleges al nivel de abstracción del API, así que no lo hagas. En general, te repito lo mismo que antes: cuando implementes documéntalo y documentar significa explicar los retos que has tenido para tomar una decisión y lo que has considerado.
> 
> Pero como empiezo a desarrollar las líneas de código para #22 si no tengo una plataforma elegida ni un lenguaje de programación

¿Cómo lo pones en la documentación si todavía no está hecho en la práctica? La documentación *documenta* lo que se ha hecho, y conviene que vaya en el mismo PR.

2023-06-28 14:10 UTC, closed without merging