Perfiles de usuario
Slowmybrosh/TFG-DietPlanner pull request #40
Opened 2023-06-23 14:11 UTC by Slowmybrosh

Como se especifica en #36 se han añadido los siguientes cambios a la documentación: 

- Descripción del problema. Se especifica el problema que se resolverá a los usuarios, concretando quienes son los mismos. 
- Siguiendo el Design thinking, se han creado los perfiles de usuario a quienes va orientada la aplicación

2023-06-23 14:12 UTC, Slowmybrosh commented
@JJ Una vez que tengo los perfiles de usuario, puedo crear las HU específicas para cada usuario?

2023-06-23 15:16 UTC, JJ commented
> @JJ Una vez que tengo los perfiles de usuario, puedo crear las HU específicas para cada usuario?

Haz lo que veas; no tienes por qué bloquearte porque algo no se haya revisado.

2023-06-28 08:43 UTC, JJ requested changes
Si recuerdas en la tutoría, teníamos que justificar por qué buscaban recetas basadas en unos cuantos ingredientes; en un caso es porque no tenían tiempo (estudiante) y en otro porque vivían lejos de supermercados y demás (Albayzín). La diferencia era el tipo de sistema que cada uno usa, y que justificaría diferentes interfaces de usuario. En ese sentido, creo que no has justificado lo suficiente por qué la persona del Albayzín necesita recetas basadas en lo que ya tiene en la despensa. También que tenga un portátil es cuestionable, porque a esa edad no se puede teclear demasiado bien. Más razonable sería un tablet. 
Recuerda en todo caso que tendrás que tener eso en cuenta más adelante cuando vayas a definir el interfaz de usuario; por ejemplo, que haya una lista de cosas comunes en la despensa en vez de teclearlas.

2023-06-28 09:00 UTC, Slowmybrosh commented
> Si recuerdas en la tutoría, teníamos que justificar por qué buscaban recetas basadas en unos cuantos ingredientes; en un caso es porque no tenían tiempo (estudiante) y en otro porque vivían lejos de supermercados y demás (Albayzín). La diferencia era el tipo de sistema que cada uno usa, y que justificaría diferentes interfaces de usuario. En ese sentido, creo que no has justificado lo suficiente por qué la persona del Albayzín necesita recetas basadas en lo que ya tiene en la despensa. También que tenga un portátil es cuestionable, porque a esa edad no se puede teclear demasiado bien. Más razonable sería un tablet. Recuerda en todo caso que tendrás que tener eso en cuenta más adelante cuando vayas a definir el interfaz de usuario; por ejemplo, que haya una lista de cosas comunes en la despensa en vez de teclearlas.

Al final la señora mayor tiene otros motivos para usar el mismo sistema, pero quiere lo mismo. Lo de la lista de ingredientes habituales sería plantearlo posteriormente. Pero se puede adaptar la interfaz a muchos tipos de dispositivo. Cambiaré el perfil de usuario para clarificarlo.

2023-06-28 09:20 UTC, Slowmybrosh commented
@JJ He clarificado el perfil de usuario, añadiendo la motivación de querer recordar recetas debido a la edad. Sobre la interfaz de usuario, crearé el ticket correspondiente y haré el diseño de la interfaz completa adaptada para diferentes dispositivos. Pero antes he de justificar porqué se hace una plataforma web. Pensando en lo que quiere el usuario y lo subiré a la implementación.

2023-06-28 10:34 UTC, JJ commented
> @JJ He clarificado el perfil de usuario, añadiendo la motivación de querer recordar recetas debido a la edad. Sobre la interfaz de usuario, crearé el ticket correspondiente y haré el diseño de la interfaz completa adaptada para diferentes dispositivos. Pero antes he de justificar porqué se hace una plataforma web. Pensando en lo que quiere el usuario y lo subiré a la implementación.

Créalo cuando sea necesario, claro.

2023-06-28 10:36 UTC, JJ approved these changes
:+1:

2023-06-28 13:46 UTC, merged