Toma de decisiones en la introducción
Slowmybrosh/TFG-DietPlanner pull request #66
Opened 2023-09-19 18:26 UTC by Slowmybrosh

Se ha añadido un párrafo explicando la toma de decisiones inicial, basada en los usuarios descritos por medio de Design Thinking. Para darle mayor coherencia a la descripción del proyecto

2023-09-19 18:28 UTC, Slowmybrosh commented
@JJ Siguiendo la sugerencia sobre donde debería estar la explicación del uso de Design Thinking, lo he añadido a la sección de la descripción del problema, en un nuevo PR para separarlo de los cambios a la planificación del capítulo de metodología

2023-09-20 10:23 UTC, JJ commented
Un PR debe *siempre* referirse a un issue. Si el issue es un comentario en un review, se puede o crear un issue con ese comentario o directamente referirse al mismo.

2023-09-20 17:29 UTC, Slowmybrosh commented
@JJ Se ha cambiado el issue del PR para que coincida de verdad con la sugerencia mencionada y solventada en este PR

2023-09-20 17:32 UTC, JJ commented
> @JJ Se ha cambiado el issue del PR para que coincida de verdad con la sugerencia mencionada y solventada en este PR

No entiendo muy bien lo que has hecho. En el *cuerpo* del PR debe *siempre* apuntar a un issue, que es el que se está tratando. Si en un mensaje de commit te refieres al #65, inclúyelo en el cuerpo del PR, que sirve para explicar cuál es el ámbito de los cambios que se están haciendo.

En cuando a ese mensaje en sí te recuerdo la necesidad de que apliques las mejores prácticas en la composición de estos mensajes, que en este caso se trata de que explique qué se ha hecho para cerrar ese issue específico y qué decisiones se han tomado.

2023-09-20 17:36 UTC, Slowmybrosh commented
En el cuerpo del PR ya estaba escrita (salvo un error y la falta de referencia al issue) como se ha resuelto el issue. He cambiado el cuerpo para referenciar al issue resuelto

2023-09-21 15:21 UTC, JJ requested changes
Por favor, consulta exactamente qué fases tiene design thinking, cómo lo estás aplicando aquí, y aclara para qué HU estás escribiendo estos párrafos y, en su caso, añade aclaraciones adicionales para ellos específicamente.

2023-09-21 15:21 UTC, JJ commented on doc/Secciones/01_Introduccion.tex
> +Por otro lado, se aplicará el enfoque del \it{\gls{design thinking}} para empatizar con el usuario y comprender a fondo el problema que están experimentando. Para ello, se debe asumir el rol de usuar
Como no está asociado el issue con el que trabajas a una historia de usuario, es difícil saber qué fin tiene este texto que se compone. Por ejemplo, si fuera para el tribunal posiblemente requeriría que se añadieran referencias o se explicaran las diferentes fases de un proceso de design thinking y cuáles se están aplicando aquí y como.

2023-09-21 18:28 UTC, Slowmybrosh commented
@JJ Se han realizado los cambios sugeridos, cuando puedas échale un vistazo porfa :)

2023-09-21 18:29 UTC, Slowmybrosh commented on doc/Secciones/01_Introduccion.tex
> +Por otro lado, se aplicará el enfoque del \it{\gls{design thinking}} para empatizar con el usuario y comprender a fondo el problema que están experimentando. Para ello, se debe asumir el rol de usuar
Se ha asociado el issue a una historia de usuario y actualizado con esta sugerencia de cara a satisfacer la historia de usuario del miembro del tribunal

2023-09-21 18:46 UTC, JJ requested changes
El principal problema es que entiendas qué es lo que hace la introducción en la memoria, y qué espera #8 encontrar ahí. Por favor, entiéndelo claramente y a partir de ahí toma una decisión sobre qué hacer con el contenido.

Por cierto, si esa decisión es "meter aquí en este PR el capítulo a donde lo voy a mover con lo que esto se va haciendo cada vez más gordo" vamos mal. Busca una forma más o menos razonable de mantener lo escrito para usarlo cuando sea conveniente, y trata de limitar el ámbito de un PR. Si has usado design thinking para precisar la descripción del problema, y este PR se limita a la descripción del problema, simplemente pon una o dos frases, una referencia y listo.

2023-09-21 18:46 UTC, JJ commented on doc/Secciones/01_Introduccion.tex
> +Por otro lado, se aplicará el enfoque del \gls{design thinking} para empatizar con el usuario y comprender a fondo el problema que están experimentando. Para ello, se debe asumir el rol de usuario y
palabras inglesas debes ponerlas en cursiva. ¿`\gls` es cursiva?

2023-09-21 18:46 UTC, JJ commented on doc/Secciones/01_Introduccion.tex
> +Se ha hablado de \gls{design thinking} sin explicar que es, para ello, se hablará un poco sobre el tema.
Agh, no digas eso. ¿NO ves que eso está buscando la pregunta "¿por qué hablas de design thinking sin explicar qué es?"

2023-09-21 18:46 UTC, JJ commented on doc/Secciones/01_Introduccion.tex
> +El concepto nació a finales del siglo XX como un compuesto que se basa en disciplinas como el diseño industrial y gráfico, además de la ingeniería y arquitectura. Este se refiere a estrategias creati
Esto es la introducción, y explicar los conceptos de forma extensa no cabe aquí. O lo explicas en metodología o en estado del arte. En la introducción o bien no lo nombras y dices que vas a usar las mejores prácticas dentro del enfoque ágil, o avanzas que vas a usar design thinking para no sé qué, y lo explicas en una frase.

2023-09-21 18:46 UTC, JJ commented on doc/Secciones/01_Introduccion.tex
> +Se compone de cinco estados que se deben usar en el proceso. Es muy importante no saltarse ningún paso
De veras. Estás en la introducción. ¿Crees que esto corresponde a la introducción?

2023-09-23 07:21 UTC, Slowmybrosh commented on doc/Secciones/01_Introduccion.tex
> +Se compone de cinco estados que se deben usar en el proceso. Es muy importante no saltarse ningún paso
No, dejaré la mención que me sugeriste a que se van a usar las mejores prácticas en el enfoque ágil.

2023-09-23 07:23 UTC, Slowmybrosh commented on doc/Secciones/01_Introduccion.tex
> +Por otro lado, se aplicará el enfoque del \gls{design thinking} para empatizar con el usuario y comprender a fondo el problema que están experimentando. Para ello, se debe asumir el rol de usuario y
No, pero lo intenté poner como palabra para el glosario y en cursiva pero LaTeX no lo detectaba bien y no cerraba la etiqueta. Haciendo que todo el texto se leyera en cursiva.

2023-09-23 07:24 UTC, Slowmybrosh commented on doc/Secciones/01_Introduccion.tex
> +Se ha hablado de \gls{design thinking} sin explicar que es, para ello, se hablará un poco sobre el tema.
Se explica el concepto en la siguiente línea, pero se eliminará esa frase para no dar lugar a confusiones.

2023-09-23 08:06 UTC, Slowmybrosh commented
@JJ Se ha eliminado toda la explicación del design thinking y la mención a ello en la descripción del problema y se añade la referencia al uso de las mejores prácticas en el enfoque ágil.

2023-09-25 16:34 UTC, JJ approved these changes
:+1:  aunque habría sido conveniente que editaras el título del PR; tampoco puedes hacer ya que se cierre el issue que estás tratando, porque el contenido ahora mismo no tiene mucho que ver con él.

Sin embargo, creo que vamos intentar acabar con el milestone 0 en vez de ir por otros vericuetos, así que mejor cerrarlo. Recuerda reorganizar los issues que no estén relacionados con el milestone 0 en otros, y también editar el milestone 0 para que refleje exactamente qué es lo que se ha terminado.

2023-09-25 16:34 UTC, JJ commented on doc/Secciones/01_Introduccion.tex
> +Para resolver el problema descrito se utilizarán las mejores prácticas dentro del enfoque ágil.
nit: No hay "el" enfoque, hay "un" enfoque.

2023-09-25 17:24 UTC, Slowmybrosh commented on doc/Secciones/01_Introduccion.tex
> +Para resolver el problema descrito se utilizarán las mejores prácticas dentro del enfoque ágil.
Antes de cerrar el PR, arreglaré eso para que no se quede olvidado

2023-09-25 17:40 UTC, merged