Especificación de la planificación
Slowmybrosh/TFG-DietPlanner pull request #68
Opened 2023-09-20 18:32 UTC by Slowmybrosh

Se soluciona el issue #67, añadiendo la planificación existente por una planificación basada en una mentalidad ágil. Exponiendo los primeros milestone del proyecto, y comentando la imposibilidad de especificar milestones más allá del objetivo propuesto.

2023-09-21 18:26 UTC, JJ requested changes
Creo que está bastante completo, pero habría que darle una vuelta con los comentarios que te indico.

2023-09-21 18:26 UTC, JJ commented on doc/Secciones/03_Metodologia.tex
> +Normalmente en un proyecto se suele especificar una planificación de antemano que cubrir, pero como se ha explicado en este capítulo, se usará una mentalidad ágil para el desarrollo del mismo. Esto s
Si dices "normalmente" #8 te va a decir que por qué no lo has hecho. En todo caso, tampoco es cierto que sea así. La metodología waterfall lo hace así.
En todo caso, siempre es mala idea incluir lo que no vas a hacer. Si lo haces, tienes que justificar por qué no lo has hecho citando algún artículo que dita que el desarrollo ágil da mejores resultados que el waterfall (y si lo haces así, habrá en #8 algún defensor del waterfall y estás jodido).

Por hacer más corta una historia larga: no uses frases negativas del tipo "no vamos a hacer esto", si lo haces, asegúrate que lo que *sí* vas a hacer tiene un buen apoyo en la literatura, y en todo caso trata de no abrir ángulos de ataque para #8, porque lo aprovecharán seguro (como bien sabes).

2023-09-21 18:26 UTC, JJ commented on doc/Secciones/03_Metodologia.tex
> +Para dar un poco más de contexto, la metodología es la que nos guía para definir el objetivo que debemos alcanzar en cada etapa del proyecto. Una vez que alcanzamos un objetivo, también nos ayuda a e
A #8 le gustan mucho las citas. Usa todas las que consideres necesarias.

2023-09-21 18:26 UTC, JJ commented on doc/Secciones/03_Metodologia.tex
> +En primer lugar se deben especificar los usuarios a los que va dirigida la solución. Se perfilarán dichos usuarios detallando su entorno, conocimientos, motivaciones, etc... Estos usuarios serán el c
ESto justifícalo porque el desarrollo ágil está centrado en el cliente.

En todo caso, esto son pasos previos a la planificación. Corresponden a la planificación de tu TFG, pero no a la planificación del desarrollo en sí.

2023-09-21 18:26 UTC, JJ commented on doc/Secciones/03_Metodologia.tex
> +Antes de echarse a definir una solución, el proyecto también requiere de una infraestructura mínima que se debe tener en cuenta para el correcto transcurso del desarrollo ágil. Como mínimo, se espera
Esta infraestructura es un producto mínimamente viable, y por tanto un milestone. Asegúrate de explicar que eso es lo que se está haciendo, tagear el último commit del milestone cuando lo hayas terminado, y enlazarlo.

2023-09-21 18:26 UTC, JJ commented on doc/Secciones/03_Metodologia.tex
> +El siguiente milestone especificado constituye permitir al usuario encontrar recetas con ciertas restricciones, para ello se establecerán pequeños subobjetivos para alcanzar el milestone y se resolve
Estás usando "el siguiente" milestone sin decir que vas a usar milestones, sin decir qué es lo que son, y sobre todo sin decir cuál es el primer milestone.

Para probar que los estás usando, enlázalos.

2023-09-21 18:26 UTC, JJ commented on doc/Secciones/03_Metodologia.tex
> +Inicialmente, se especifican los milestones mencionados, pero debido a la mentalidad ágil es imposible planificar milestones más allá, porque no se sabe que necesidades tendrá el usuario a lo largo d
... y por tanto se especificarán en la sección de implementación.

2023-09-21 18:26 UTC, JJ commented on doc/Secciones/03_Metodologia.tex
> +    \item Descripción del problema.
Los milestones siempre tienen que ser productos mínimamente viables.

2023-09-24 17:59 UTC, Slowmybrosh commented on doc/Secciones/03_Metodologia.tex
> +Normalmente en un proyecto se suele especificar una planificación de antemano que cubrir, pero como se ha explicado en este capítulo, se usará una mentalidad ágil para el desarrollo del mismo. Esto s
Se ha revisado este párrafo eliminando cualquier referencia a cosas que NO se van a realizar, según lo especificado en #70

2023-09-24 18:00 UTC, Slowmybrosh commented on doc/Secciones/03_Metodologia.tex
> +Para dar un poco más de contexto, la metodología es la que nos guía para definir el objetivo que debemos alcanzar en cada etapa del proyecto. Una vez que alcanzamos un objetivo, también nos ayuda a e
Se buscarán citas útiles que expliquen en que se basa una metodología. Y más específicamente una metodología ágil.

2023-09-24 19:16 UTC, Slowmybrosh commented on doc/Secciones/03_Metodologia.tex
> +Antes de echarse a definir una solución, el proyecto también requiere de una infraestructura mínima que se debe tener en cuenta para el correcto transcurso del desarrollo ágil. Como mínimo, se espera
Se especificará que constituye el primer milestone del proyecto y se enlazará cuando se concluya el trabajo en dicho milestone. ¿Por enlazar el commit a que te refieres, a sacar el enlace y especificarlo en la memoria para que el tribunal pueda acceder a él facilmente?

2023-09-24 19:17 UTC, Slowmybrosh commented on doc/Secciones/03_Metodologia.tex
> +En primer lugar se deben especificar los usuarios a los que va dirigida la solución. Se perfilarán dichos usuarios detallando su entorno, conocimientos, motivaciones, etc... Estos usuarios serán el c
Se especificará que está centrado en el cliente, para dejarlo claro al tribunal y se quitará la planificación que no corresponda al proyecto.

2023-09-24 19:19 UTC, Slowmybrosh commented on doc/Secciones/03_Metodologia.tex
> +El siguiente milestone especificado constituye permitir al usuario encontrar recetas con ciertas restricciones, para ello se establecerán pequeños subobjetivos para alcanzar el milestone y se resolve
No quedó claro que el primer milestone lo constituye la infraestructura, se cambiará para dejarlo claro y enlazará para probar que se están usando

2023-09-24 19:50 UTC, Slowmybrosh commented
@JJ Cuando puedas echale un vistazo a las mejoras añadidas

2023-09-25 15:52 UTC, JJ commented
De veras, intenta usar los mensajes de commit para lo que son, explicar las decisiones tomadas. Mensajes como este [943ac97](https://github.com/Slowmybrosh/TFG-DietPlanner/pull/68/commits/943ac979d9b46ccd6ebc2fd1a500ea4999e06742) no ayudan absolutamente nada. También deberían ser atómicos en el sentido de que cada issue debería cerrarse con un solo commit.
Las buenas prácticas ayudan a que el resto del equipo (bueno, yo) entienda mejor por qué se ha hecho algo, y por tanto hay que darles la importancia que merecen.

2023-09-25 15:53 UTC, JJ commented on doc/Secciones/03_Metodologia.tex
> +El siguiente milestone especificado constituye permitir al usuario encontrar recetas con ciertas restricciones, para ello se establecerán pequeños subobjetivos para alcanzar el milestone y se resolve
Siempre tienes que tener la máxima precisión en al memoria. También los términos ingleses suelen ponerse en cursiva.

2023-09-25 17:31 UTC, merged