Añadido uso de cherry-picking y design thinking a metodología
Slowmybrosh/TFG-DietPlanner pull request #74
Opened 2023-09-26 18:16 UTC by Slowmybrosh

Se añaden las siguientes mejoras:
- Se han añadido las secciones relativas al uso de la operación cherry-pick (#73), explicando de que se trata y el uso que se le ha dado dentro del proyecto
- Añadida explicación, etapas y uso de design thinking en el proyecto (#65) como parte de la explicación de la metodología utilizada en el proyecto.

2023-09-26 18:19 UTC, Slowmybrosh commented
@JJ Se han añadido los cambios mencionados en el cuerpo del PR, échale un vistazo cuando puedas 🚀

2023-09-27 07:48 UTC, JJ requested changes
Por favor, trata de estructurar un poco mejor toda la sección para que las diferentes metodologías y buenas prácticas encajen dentro de la fase del proyecto en las que se han usado (que es de lo que va el capítulo)

2023-09-27 07:48 UTC, JJ commented on doc/Secciones/03_Metodologia.tex
> +\section{Operaciones utilizadas en el proyecto}
Sería mejor que esto lo contaras cuando hables del momento en el que lo has necesitado; por ejemplo, para pasar de un milestone a otro. Más que una "lista de la compra de operaciones" deberías incluir cada una de ellas en donde sea conveniente.

2023-09-27 07:48 UTC, JJ commented on doc/Secciones/03_Metodologia.tex
> +\subsection{Cherry-picking}
Por ejemplo, esto está relacionado con la incorporación de código una vez revisado.

2023-09-27 07:48 UTC, JJ commented on doc/Secciones/03_Metodologia.tex
> +\section{Design Thinking}
Esto está relacionado con el análisis del problema.

2023-09-27 07:48 UTC, JJ commented on doc/Secciones/03_Metodologia.tex
>  \section{User journeys}
User Journey es una metodología como otra cualquiera, o una "operación"

2023-09-30 17:12 UTC, Slowmybrosh commented
Se ha reorganizado el capítulo con el orden seguido en el proyecto #75:
- Se ha movido la sección Design thinking y se han especificado los pasos relacionados con el análisis del problema.
- Se organizan los user journeys y los perfiles de usuarios en etapas de design thiking
- Se mueve el uso de git en el proyecto y se añade la definición de cherry-pick, su uso y cuando se ha usado en el proyecto

2023-09-30 17:13 UTC, Slowmybrosh commented on doc/Secciones/03_Metodologia.tex
>  \section{User journeys}
Se mueve User journeys y perfiles de usuario a design thinking

2023-09-30 17:15 UTC, Slowmybrosh commented
@JJ Se ha incluido cherry-pick en la explicación del uso de git en el proyecto: Cuando, porque y como se ha usado. A parte de reorganizar el capítulo. Si ves que la inclusión de cherry pick no queda bien en este capítulo se puede apartar y mover al capítulo de implementación

2023-10-02 05:25 UTC, JJ approved these changes
Tienes que mirar al índice del capítulo y comprobar que las cosas que están en la lista al mismo nivel tienen sentido. Yo veo "git" al mismo nivel que "design thinking"; todos tienen que tener sentido debajo del título del capítulo: "Metodología"
No acabo de verlo; ten en cuenta que una de las cosas que van a evaluar en #8 va a ser la expresión escrita, que incluye la estructuración correcta. Si el capítulo se llama metodología, van a esperar encontrar una narración que cuente el marco general de la metodología (desarrollo ágil), así como el marco en el que se han escogido diferentes metodologías (git dentro de una metodología que puede ser gitflow u otra parecida, design thinking en la fase de definición del producto, y otras metodologías (en plural) dentro de otras fases.
En todo caso, el desarrollo ágil va por los productos mínimamente viables, y este lo es. Pero recuerda que la redacción actual no garantiza un buen resultado en el producto final. Yo te aconsejaría que crearas un milestone final que incluyera revisión de la redacción de la memoria.

2023-10-02 05:25 UTC, JJ commented on doc/Secciones/03_Metodologia.tex
>  \chapter{Descripción de la metodología}
En realidad, estás describiendo varias metodologías, no hay una sola.

2023-10-02 05:25 UTC, JJ commented on doc/Secciones/03_Metodologia.tex
> +En el proyecto, se aplicará el enfoque del \gls{design thinking}, en el que sus primeros pasos implican realizar un análisis del problema empatizando con los usuarios y definiéndolos detalladamente.
Se define más el problema que los usuarios, pero tambien los usuarios, claro. Para definir los usuarios, sin embargo, se suele usar la metodología de *personas*

2023-10-02 05:25 UTC, JJ commented on doc/Secciones/03_Metodologia.tex
> +\subsection{2. Definir - Perfiles de usuarios}
¿La subsection no va a su vez numerada? Si es así, usa cosas como "Fase 2 de design thinking:"

2023-10-03 17:37 UTC, Slowmybrosh commented on doc/Secciones/03_Metodologia.tex
> +\subsection{2. Definir - Perfiles de usuarios}
Esto es una typo, lo arreglo

2023-10-03 17:53 UTC, Slowmybrosh commented on doc/Secciones/03_Metodologia.tex
>  \chapter{Descripción de la metodología}
Se cambiará el nombre del capítulo por "Metodología"

2023-10-03 18:00 UTC, JJ commented on doc/Secciones/03_Metodologia.tex
>  \chapter{Descripción de la metodología}
¿Has considerado ponerlo en plural?

2023-10-03 18:12 UTC, Slowmybrosh commented on doc/Secciones/03_Metodologia.tex
>  \chapter{Descripción de la metodología}
Me parece bien, lo dejo en plural

2023-10-03 18:14 UTC, Slowmybrosh commented on doc/Secciones/03_Metodologia.tex
> +En el proyecto, se aplicará el enfoque del \gls{design thinking}, en el que sus primeros pasos implican realizar un análisis del problema empatizando con los usuarios y definiéndolos detalladamente.
Este es el método que se utilizó pero no recordaba exactamente el nombre, de ahí que no se nombre como tal, voy a especificarlo y en el apartado de definición de usuarios escribir que es la metodología de persona añadiendo la cita correspondiente.

2023-10-03 18:54 UTC, Slowmybrosh commented
Se realizan las siguientes mejoras: 

- Se cambia el nombre del capítulo de "Descripción de la metodología" a "Metodologías"
- Se corrige una typo numerando subsecciones ya numeradas en design thinking
- Se menciona el uso de la metodología de personas y se detalla que es en el apartado de definición de design thinking

2023-10-03 18:55 UTC, Slowmybrosh commented
@JJ Habiendo introducido las mejoras finales mencionadas, procedo a cerrar el PR y con ello el milestone.

2023-10-04 18:00 UTC, merged