Definición del Milestone 0
Slowmybrosh/TFG-DietPlanner pull request #76
Opened 2023-10-04 21:54 UTC by Slowmybrosh

Se realizan los siguientes cambios: 

- Se crea un capítulo "implementación" con los detalles del milestone 0 (#46) (#54)  narrado las decisiones tomadas en los capítulos que engloban al milestone 0

2023-10-04 21:55 UTC, Slowmybrosh commented
@JJ Cuando puedas échale un vistazo a esto :)

2023-10-05 11:30 UTC, JJ requested changes
Por favor, considera diferentes posibilidades para incluir correctamente los contenidos donde #8 espera encontrarlos.

2023-10-05 11:30 UTC, JJ commented on doc/Secciones/04_Implementacion.tex
> +\section{\href{https://github.com/Slowmybrosh/TFG-DietPlanner/milestone/1}{Milestone 0} - Documentación inicial}
No sé si te lo comenté ya, pero los primeros milestones son más bien parte de la planificación, más que de la implementación. "Documentación inicial" difícilmente se puede considerar como algo implementado, ¿no?

2023-10-05 11:30 UTC, JJ commented on doc/Secciones/04_Implementacion.tex
> +Para el proyecto se plantea el uso de \emph{design thinking}, realizando una pequeña investigación leyendo diversos artículos académicos\cite{wolniak2017design}\cite{thoring2011understanding} que han
¿De qué forma crees que esto forma parte de la implementación? ¿No será más bien planificación del proyecto?

2023-10-05 11:31 UTC, JJ commented
Adicionalmente, no parece que el PMV en el que estamos trabajando incluya nada relacionado con la implementación (ni, para el caso, la planificación). Por favor, considera incluir este PR en otro milestone (pero también describir con más corrección el M1 para que incluya, entre otras cosas, la documentación inicial del proyecto.

2023-10-05 19:09 UTC, Slowmybrosh commented
@JJ Se cambia el capítulo debido a que su contenido no pertenece al ámbito de implementación, se ha renombrado el capítulo a "planificación".

Adicionalmente se cambia el milestone de este PR a M0 y al completarlo, se considerará completado el M0.

2023-10-06 06:46 UTC, JJ approved these changes
👍

2023-10-07 17:30 UTC, merged