Implementación - Lenguaje de programación
Slowmybrosh/TFG-DietPlanner pull request #77
Opened 2023-10-07 18:49 UTC by Slowmybrosh

- Se crea el capítulo de implementación
- Se especifica el lenguaje de programación elegido para el proyecto (#51), justificando debidamente su elección

2023-10-07 18:50 UTC, Slowmybrosh commented
@JJ Cuando puedas échale un vistazo a esto :)

2023-10-09 08:07 UTC, JJ commented
Si es implementación, ¿sigue siendo parte de la infraestructura inicial?

2023-10-09 08:20 UTC, JJ commented
Que escribas la memoria a la vez que haces el trabajo es siempre una buena idea; sin embargo, si no acomodas esa parte escrita en el momento del desarrollo que corresponda, puedes acabar haciendo cosas que luego tienes que rehacer o acomodar. Así que tienes dos opciones (posiblemente más)
1. O dejas claro que vas a documentar *todo* a la vez que lo haces, en cuyo caso el PMV en el que estés trabajando tiene que incluir la documentación.
2. O te limitas a lo que has puesto en el milestone, abres una rama con la documentación, y la incorporas más adelante cuando llegues a eso.

En todo caso, puedes separar la elección del lenguaje de programación de la elección del gestor de tareas que vayas a usar. poetry lo puedes usar como gestor de tareas aunque luego vayas a usar Ruby. 

Por favor, trata de entender que la organización en milestones tiene su utilidad para el desarrollo y organización del proyecto. Si no asumes esto, es difícil que lo uses correctamente.

2023-10-09 08:23 UTC, JJ requested changes
Este tipo de justificaciones tampoco servían en IV. Como en IV, no se trata de que cuentes cosas para rellenar el TFG. Se trata de que expliques el proceso de decisión que te ha llevado a un lenguaje y no a otro. Si no has llevado a cabo ese proceso, escribir cosas como si lo hubieras hecho no ayuda absolutamente nada al tribunal a evaluarte, ni a mi tampoco. Así que, por favor, revisa los apuntes correspondientes de IV (y los errores frecuentes en el objetivo 3, sobre todo) para ver cómo se toma una decisión técnica y cómo se expone la misma en una memoria del TFG.

2023-10-09 08:23 UTC, JJ commented on doc/Secciones/05_Implementacion.tex
> +Para el desarrollo de la solución, de cualquier tipo, es necesario definir un lenguaje de programación. El lenguaje utilizado en el proyecto será \Gls{python}.
No aportas ninguna informació sobre por qué tomas esta decisión. Es cierto que (incorrectamente) el 90% de los TFGs son así. Pero una de las cosas que evalúa #8 es que se hayan justificado correctamente las decisiones tomadas.

2023-10-09 18:00 UTC, Slowmybrosh commented on doc/Secciones/05_Implementacion.tex
> +Para el desarrollo de la solución, de cualquier tipo, es necesario definir un lenguaje de programación. El lenguaje utilizado en el proyecto será \Gls{python}.
Se corrige y especifican los criterios técnicos utilizados en la decisión del lenguaje

2023-10-09 18:01 UTC, Slowmybrosh commented
> Que escribas la memoria a la vez que haces el trabajo es siempre una buena idea; sin embargo, si no acomodas esa parte escrita en el momento del desarrollo que corresponda, puedes acabar haciendo cosas que luego tienes que rehacer o acomodar. Así que tienes dos opciones (posiblemente más)
> 
> 1. O dejas claro que vas a documentar _todo_ a la vez que lo haces, en cuyo caso el PMV en el que estés trabajando tiene que incluir la documentación.
> 2. O te limitas a lo que has puesto en el milestone, abres una rama con la documentación, y la incorporas más adelante cuando llegues a eso.
> 
> En todo caso, puedes separar la elección del lenguaje de programación de la elección del gestor de tareas que vayas a usar. poetry lo puedes usar como gestor de tareas aunque luego vayas a usar Ruby.
> 
> Por favor, trata de entender que la organización en milestones tiene su utilidad para el desarrollo y organización del proyecto. Si no asumes esto, es difícil que lo uses correctamente.

Considero que es más sencilla la segunda opción debido a que las decisiones tomadas deberían añadirse junto con la implementación para asegurar la coherencia de las decisiones tomadas, ya que de hacerlo al final del milestone puede empeorar la coherencia a la hora de plasmar la decisión en la memoria

2023-10-09 18:02 UTC, Slowmybrosh commented
Se introducen los siguientes cambios: 

- Se ha modificado el nombre del milestone de "Infraestructura inicial" a "Infraestructura", inicialmente se especificó así porque tampoco se sabe si será necesario un gestor de variables de entorno, o cualquier añadido en la infraestructura.

- Se ha especificado en el milestone de 'Infraestructura' que se debe escribir la documentación junto con la implementación de las herramientas utilizadas. Además, considero que es más sencillo implementar y razonar en la documentación justificando las decisiones tomadas en el momento de implementar y no al final del milestone donde puede que la justificación no sea tan coherente.

- Se ha justificado de manera organizada, la decisión técnica para elegir Python como lenguaje de programación, según los criterios sugeridos en el objetivo 3 de IV. 

- Se ha cambiado el milestone asignado a #51  y este PR de 'Infraestructura' a 'Lenguaje de programación' para establecer la importancia y el hito de definir un lenguaje de programación. Se han especificado los objetivos esperados de este milestone y los criterios que debe cumplir el lenguaje de programación elegido, documentando adecuadamente la decisión para la correcta comprensión de #8.

2023-10-09 18:05 UTC, Slowmybrosh commented
@JJ Cuando puedas échale un vistazo a esto

2023-10-09 18:12 UTC, Slowmybrosh commented
> > > Que escribas la memoria a la vez que haces el trabajo es siempre una buena idea; sin embargo, si no acomodas esa parte escrita en el momento del desarrollo que corresponda, puedes acabar haciendo cosas que luego tienes que rehacer o acomodar. Así que tienes dos opciones (posiblemente más)
> > > 
> > > 1. O dejas claro que vas a documentar _todo_ a la vez que lo haces, en cuyo caso el PMV en el que estés trabajando tiene que incluir la documentación.
> > > 2. O te limitas a lo que has puesto en el milestone, abres una rama con la documentación, y la incorporas más adelante cuando llegues a eso.
> > > 
> > > En todo caso, puedes separar la elección del lenguaje de programación de la elección del gestor de tareas que vayas a usar. poetry lo puedes usar como gestor de tareas aunque luego vayas a usar Ruby.
> > > Por favor, trata de entender que la organización en milestones tiene su utilidad para el desarrollo y organización del proyecto. Si no asumes esto, es difícil que lo uses correctamente.
> > 
> > 
> > Considero que es más sencilla la segunda opción debido a que las decisiones tomadas deberían añadirse junto con la implementación para asegurar la coherencia de las decisiones tomadas, ya que de hacerlo al final del milestone puede empeorar la coherencia a la hora de plasmar la decisión en la memoria
> 
> Esa es la primera opción, ¿no?

Si, es la primera opción. En los milestones está especificado como requisito el contar con la documentación relativa a las herramientas de la infraestructura a medida que se implementen, en vez de al final.

2023-10-09 18:15 UTC, JJ requested changes
Creo que dado que este PR no está todavía en un estado en el que se vaya a fusionar, es mejor que te centres en crear el capítulo de implementación *antes* en el milestone correspondiente.
Entre otras cosas, tendrás que incluir todas las otras decisiones que has tomado hasta ahora, desde el uso de GitHub (y no GitLab) al uso de un sistema de CI (GitHub Actions) y demás, que son también decisiones. Cuando terminemos con ese volvemos a este, si te parece.

2023-10-09 18:15 UTC, JJ commented on doc/Secciones/05_Implementacion.tex
> +En todo proyecto existen una serie de decisiones que marcan el avance del proyecto. En este capítulo se describirán, detalladamente, las justificaciones de cada decisión que se tome durante el desarr
Esto claramente *no* corresponde a este milestone, estás creando un fichero y añadiendo una introducción, totalmente fuera del ámbito que es la decisión sobre un lenguaje de programación. En todo caso no le vamos a dar más vueltas, pero por favor trata de respetar el ámbito de cada PR y organizar el código y la documentación de forma sistemática.

Si lo que quieres es escribir las decisiones que tomes en el capítulo de implementación en cuanto que las tomes, lo correcto habría sido crear un issue específico que exprese un problema como "Las decisiones de implementación tienen que incluirse en su capítulo correspondiente de forma que quede claro su secuencia y el punto en el que se han tomado y por qué". Ese issue debería haber ido en un milestone con la estructura inicial de la memoria, que podría ser el 0

2023-10-09 18:15 UTC, JJ commented on doc/Secciones/05_Implementacion.tex
> +    \item Estándares del lenguaje
¿En qué sentido se considerarán los estándares?

2023-10-09 18:15 UTC, JJ commented on doc/Secciones/05_Implementacion.tex
> +Python es un lenguaje de alto nivel de propósito genera, que está cada vez más extendido. Su sintaxis permite a los desarrolladores escribir código más simple que el que se podría escribir en \Gls{c}
Has puesto los criterios y a continuación has procedido a ignorarlos (y a dejar "genera" en vez de general). ¿Aporta alguna información a quien esté tratando de entender tu decisión que "tiene un tipo dinámico de dato"?

2023-10-17 16:45 UTC, Slowmybrosh commented
@JJ Se ha cambiado la decisión del lenguaje a como hablamos, se ha elegido Python como lenguaje de desarrollo

2023-10-19 17:40 UTC, merged