Mejoras
Slowmybrosh/TFG-DietPlanner pull request #99
Opened 2023-11-12 11:45 UTC by Slowmybrosh

Se implementan las siguientes mejoras: 
- #98 Se añade una herramienta para la prueba de carga, con la correspondiente documentación. 
  - Se cambia la manera en la que se genera el PDF para que sea recuperado fácilmente por cualquier persona que compruebe el proyecto.

2023-11-12 11:49 UTC, Slowmybrosh commented
@JJ Se ha añadido la prueba de carga con la herramienta Locust, en vez de Jmeter, ya que simplifica mucho la manera de componer las tareas para el test. Como solo se ha añadido esta pequeña parte de manera razonada y explicando su uso y resultados como mejora del proyecto orientada a #8.

2023-11-12 17:06 UTC, JJ requested changes
Los binarios *nunca* van en el repositorio si se pueden generar a partir dle mismo.
Tampoco es buena práctica añadir ficheros en el directorio raíz.

2023-11-12 17:06 UTC, JJ commented on pyproject.toml
> +locust = "^2.18.2"
No parece que esta sea una dependencia de producción. Ni, para el caso, algunas de las que están más arriba.

2023-11-12 17:06 UTC, JJ commented on doc/Secciones/08_Pruebas.tex
> +En la imágen se observa como la aplicación aguanta hasta setecientos usuarios, teniendo problemas entre seiscientos y setecientos usuarios, hasta que al final el servidor no puede más y deja de poder
¿Esto ha pasado el corrector ortográfico?

2023-11-12 17:49 UTC, Slowmybrosh commented on pyproject.toml
> +locust = "^2.18.2"
Se revisarán las dependencias y se eliminarán las prescindibles

2023-11-12 17:49 UTC, Slowmybrosh commented on doc/Secciones/08_Pruebas.tex
> +En la imágen se observa como la aplicación aguanta hasta setecientos usuarios, teniendo problemas entre seiscientos y setecientos usuarios, hasta que al final el servidor no puede más y deja de poder
Si, no sé porque pasó los test, pero se cambiará

2023-11-12 17:57 UTC, Slowmybrosh commented
@JJ Se han realizado las sugerencias, revisado las dependencias del proyecto, arreglado la falta de ortografía que no se detectó con el corrector y se han eliminado todos los ficheros posibles de la raíz del proyecto

2023-11-13 06:07 UTC, merged

2023-11-13 07:15 UTC, JJ commented on pyproject.toml
> +locust = "^2.18.2"
No se trata de eso, sino de que hay dependencias de producción y otras de desarrollo.

2023-11-13 07:15 UTC, JJ commented
No he aprobado este PR, me temo. Si lo has fusionado, bajo tu responsabilidad.

2023-11-13 07:18 UTC, Slowmybrosh commented
Lo he fusionado porque voy a estar todo dl día fuera trabajando y lo tengo que entregar hoy

2023-11-13 07:19 UTC, JJ commented on pyproject.toml
> -invoke = "^2.1.3"
Esto sería una dependencia de desarrollo, igual que locust. Aunque en este último caso ni siquiera lo estás usando para el desarrollo, sino para un script; sin embargo, ese script debería ser parte del proceso de desarrollo. Tal como lo has dejado ahora mismo no se podría reproducir.
invoke sí puede estar aquí, ¿por qué no? Lo vas a usar sólo desde poetry.

2023-11-13 07:20 UTC, JJ commented on dietplanner/db.sqlite3
Los ficheros binarios no deben ir en el repo. Si es la consecuencia de un milestone, almacénalo en ese release, por ejemplo.

2023-11-13 07:22 UTC, JJ commented
> Lo he fusionado porque voy a estar todo dl día fuera trabajando y lo tengo que entregar hoy

Puedes generar un release simplemente tageando, te genera un tgz automáticamente. En el caso de repositorios ni siquiera es necesario, basta con poner un enlace en un PDF.
En todo caso, sólo estoy diciendo lo obvio: yo no he aprobado el PR, es responsabilidad tuya haberlo fusionado.